const C=window.CDL_CONFIG||{};
const configured=Boolean(C.supabaseUrl&&C.supabaseAnonKey);
const db=configured?window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey):null;
const NUCLEI=['CDL Mulher','CDL Jovem','CDL Innova','CDL Cultura','Caminhos de Hamburgo Velho','Conselho','Diretoria','Outro'];
const SECTORS=['Marketing e Comunicação','Comercial','Relacionamento e Atendimento','Financeiro e Administrativo','TI, CRM e Automação','Eventos','Gestão Executiva','Presidência e Conselho','Outro'];
const PRIORITIES=['Urgente','Alta','Média','Baixa'];
const STATUSES=['Não iniciado','Em andamento','Aguardando retorno','Concluído','Cancelado'];
let session=null, demands=[], profile=null, activeScope='all', viewMode='table',notificationTimer=null,notifications=[],soundEnabled=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fillSelect(el,items,first='Selecione'){el.innerHTML=`<option value="">${first}</option>`+items.map(v=>`<option>${esc(v)}</option>`).join('')}
fillSelect($('[name=nucleus]'),NUCLEI);fillSelect($('[name=sector]'),SECTORS);fillSelect($('[name=priority]'),PRIORITIES);$('[name=priority]').value='Média';
fillSelect($('#filterStatus'),STATUSES,'Todos os status');fillSelect($('#filterNucleus'),NUCLEI,'Todos os núcleos');fillSelect($('#filterPriority'),PRIORITIES,'Todas as prioridades');
fillSelect($('#filterSector'),SECTORS,'Todos os setores');
fillSelect($('#editForm [name=nucleus]'),NUCLEI);fillSelect($('#editForm [name=sector]'),SECTORS);fillSelect($('#editForm [name=priority]'),PRIORITIES);fillSelect($('#editForm [name=status]'),STATUSES);
function route(){const id=location.hash.replace('#/','')||'inicio';$$('.view').forEach(v=>v.classList.add('hidden'));if(!configured){$('#setup').classList.remove('hidden');return}const protectedView=['plano','ideias','dashboard','usuarios'].includes(id);if(protectedView&&!session){location.hash='#/login';return}if(id==='usuarios'&&profile?.role!=='admin'){location.hash='#/plano';return}$('#'+(document.getElementById(id)?id:'inicio')).classList.remove('hidden');if(id==='plano')loadWorkspace();if(id==='ideias'&&typeof loadIdeas==='function')loadIdeas();if(id==='dashboard')loadDemands(true);if(id==='usuarios')loadProfiles()}
function setAuthUI(){$$('.admin-only').forEach(x=>x.classList.toggle('hidden',!session));$('#usersNav').classList.toggle('hidden',!session||profile?.role!=='admin');$('#notificationCenter').classList.toggle('hidden',!session);$('#authButton').textContent=session?'Sair':'Área administrativa'}
window.addEventListener('hashchange',route);
$('#authButton').onclick=async()=>{if(session){stopNotifications();await db.auth.signOut();session=null;setAuthUI();location.hash='#/inicio'}else location.hash='#/login'};
$('#demandForm').onsubmit=async e=>{e.preventDefault();const btn=$('#sendButton'),msg=$('#formMessage');btn.disabled=true;msg.className='message';msg.textContent='Registrando...';const f=Object.fromEntries(new FormData(e.currentTarget));const {data,error}=await db.rpc('submit_demand',{p_requester:f.requester,p_email:f.email||null,p_nucleus:f.nucleus,p_sector:f.sector,p_description:f.description,p_expected_result:f.expected_result,p_deadline:f.deadline,p_priority:f.priority,p_notes:f.notes||null});btn.disabled=false;if(error){msg.classList.add('error');msg.textContent='Não foi possível registrar. '+error.message;return}msg.classList.add('success');msg.textContent=`Demanda registrada com sucesso. Protocolo ${data}.`;e.currentTarget.reset();$('[name=priority]').value='Média'};
$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),msg=$('#loginMessage');msg.textContent='Entrando...';const {data,error}=await db.auth.signInWithPassword({email:f.email,password:f.password});if(error){msg.className='message error';msg.textContent='E-mail ou senha inválidos.';return}session=data.session;await loadProfile();setAuthUI();location.hash='#/plano'};
async function loadProfile(){profile=null;if(!session)return;const {data,error}=await db.from('profiles').select('name,sector,role,active').eq('id',session.user.id).maybeSingle();if(!error&&data?.active!==false)profile=data;activeScope=profile?.role==='admin'?'all':profile?.sector?'sector':'all';if(profile?.role==='admin')clearDemandFilters();$('#planGreeting').textContent=profile?.role==='admin'?`Olá, ${profile.name||'administrador'}. Você está na visão Geral e pode acompanhar todas as demandas da CDL.`:profile?.name?`Olá, ${profile.name}. Acompanhe as demandas do seu setor e da CDL.`:'Acompanhe e atualize as solicitações em um único ambiente.';startNotifications()}
async function loadWorkspace(){await loadProfile();await loadDemands()}
async function loadProfiles(){const {data,error}=await db.from('profiles').select('*').order('name');if(error){toast('Não foi possível carregar os usuários. Execute a atualização do banco.');return}const rows=data||[];$('#emptyProfiles').classList.toggle('hidden',rows.length>0);$('#profileRows').innerHTML=rows.map(p=>`<tr><td><input data-profile="${p.id}" data-profile-field="name" value="${esc(p.name||'')}" placeholder="Nome"></td><td>${esc(p.email||'')}</td><td><select data-profile="${p.id}" data-profile-field="sector"><option value="">Sem setor</option>${SECTORS.map(x=>`<option ${x===p.sector?'selected':''}>${esc(x)}</option>`).join('')}</select></td><td><select data-profile="${p.id}" data-profile-field="role"><option value="collaborator" ${p.role==='collaborator'?'selected':''}>Colaborador</option><option value="manager" ${p.role==='manager'?'selected':''}>Gestor</option><option value="admin" ${p.role==='admin'?'selected':''}>Administrador</option></select></td><td><input class="active-check" type="checkbox" data-profile="${p.id}" data-profile-field="active" ${p.active?'checked':''}></td></tr>`).join('');$$('[data-profile-field]').forEach(x=>x.onchange=()=>updateProfile(x))}
async function updateProfile(el){el.disabled=true;const value=el.type==='checkbox'?el.checked:(el.value||null);const {error}=await db.from('profiles').update({[el.dataset.profileField]:value,updated_at:new Date().toISOString()}).eq('id',el.dataset.profile);el.disabled=false;toast(error?'Erro ao atualizar usuário: '+error.message:'Usuário atualizado.')}
async function loadDemands(toDashboard=false){let result=profile?.role==='admin'?await db.rpc('list_admin_demands'):await db.from('demands').select('*').order('deadline',{ascending:true});if(result.error&&profile?.role==='admin')result=await db.from('demands').select('*').order('deadline',{ascending:true});const {data,error}=result;if(error){toast(error.message);return}demands=(data||[]).sort((a,b)=>String(a.deadline).localeCompare(String(b.deadline)));if(toDashboard)renderDashboard();else renderTable()}
function clearDemandFilters(){['search','filterStatus','filterNucleus','filterSector','filterPriority'].forEach(id=>{const el=$('#'+id);if(el)el.value=''});activeScope='all'}
function userName(){return profile?.name||session?.user?.email?.split('@')[0]||''}
function inScope(d,scope=activeScope){const today=new Date().toISOString().slice(0,10),isActive=d.active!==false;if(scope==='inactive')return profile?.role==='admin'&&!isActive;if(!isActive)return false;if(scope==='sector')return profile?.sector?d.sector===profile.sector:true;if(scope==='mine')return normalizeHeader(d.assignee)===normalizeHeader(userName());if(scope==='late')return d.deadline<today&&!['Concluído','Cancelado'].includes(d.status);if(scope==='done')return d.status==='Concluído';return true}
function filtered(){const q=$('#search').value.toLowerCase(),s=$('#filterStatus').value,n=$('#filterNucleus').value,t=$('#filterSector').value,p=$('#filterPriority').value;return demands.filter(d=>inScope(d)&&(!q||`${d.protocol} ${d.description} ${d.requester} ${d.assignee||''} ${d.notes||''}`.toLowerCase().includes(q))&&(!s||d.status===s)&&(!n||d.nucleus===n)&&(!t||d.sector===t)&&(!p||d.priority===p))}
function options(items,current){return items.map(x=>`<option ${x===current?'selected':''}>${esc(x)}</option>`).join('')}
function priorityClass(p){return {Urgente:'urgent',Alta:'high','Média':'medium',Baixa:'low'}[p]||'low'}
function scopeCount(scope){return demands.filter(d=>inScope(d,scope)).length}
function renderScopeTabs(){$$('#scopeTabs button').forEach(b=>{if(b.dataset.scope==='inactive')b.classList.toggle('hidden',profile?.role!=='admin');b.classList.toggle('active',b.dataset.scope===activeScope);b.querySelector('span').textContent=scopeCount(b.dataset.scope);if(b.dataset.scope==='sector'){b.firstChild.textContent=profile?.sector?`${profile.sector} `:'Meu setor ';b.disabled=!profile?.sector}})}
function renderTable(){const rows=filtered();renderScopeTabs();$('#resultCount').textContent=`${rows.length} ${rows.length===1?'demanda':'demandas'}`;$('#viewHint').textContent=viewMode==='kanban'?'Arraste os cartões entre as colunas para atualizar o status.':'As alterações feitas na tabela são salvas automaticamente.';$('#emptyTable').classList.toggle('hidden',rows.length>0);$('#demandRows').innerHTML=rows.map(d=>`<tr><td><strong>${esc(d.protocol)}</strong><br><small>${esc(d.sector)}</small></td><td class="demand-cell"><strong title="${esc(d.description)}">${esc(d.description)}</strong><br><small>${esc(d.requester)} · ${new Date(d.created_at).toLocaleDateString('pt-BR')}</small></td><td><input class="date-input" type="date" data-id="${d.id}" data-field="deadline" value="${esc(d.deadline)}"></td><td><select data-id="${d.id}" data-field="priority">${options(PRIORITIES,d.priority)}</select></td><td><select data-id="${d.id}" data-field="status">${options(STATUSES,d.status)}</select></td><td><input data-id="${d.id}" data-field="assignee" value="${esc(d.assignee||'')}" placeholder="Definir responsável"></td><td><button class="row-action" data-edit="${d.id}">Abrir</button></td></tr>`).join('');renderKanban(rows);bindWorkspaceControls()}
function statusSlug(status){return {'Não iniciado':'not-started','Em andamento':'in-progress','Aguardando retorno':'waiting','Concluído':'completed','Cancelado':'cancelled'}[status]||'not-started'}
function renderKanban(rows=filtered()){const groups=STATUSES;$('#kanbanView').innerHTML=groups.map(status=>{const cards=rows.filter(d=>d.status===status),slug=statusSlug(status);return `<section class="kanban-column ${slug}" data-drop-status="${esc(status)}"><header><div><i></i><strong>${esc(status)}</strong></div><span>${cards.length}</span></header><div class="kanban-dropzone">${cards.map(d=>`<article class="kanban-card summary-card" draggable="true" data-demand-id="${d.id}" data-edit="${d.id}"><div><strong>${esc(d.protocol)}</strong><span class="badge ${priorityClass(d.priority)}">${esc(d.priority)}</span></div><dl><div><dt>Quem cadastrou</dt><dd>${esc(d.requester)}</dd></div><div><dt>Finalidade</dt><dd class="summary-purpose" title="${esc(d.expected_result)}">${esc(d.expected_result)}</dd></div><div><dt>Responsável</dt><dd>${esc(d.assignee||'Não definido')}</dd></div><div><dt>Data de registro</dt><dd>${new Date(d.created_at).toLocaleDateString('pt-BR')}</dd></div><div><dt>Status</dt><dd>${esc(d.status)}</dd></div></dl></article>`).join('')||'<p class="column-empty">Solte uma demanda aqui</p>'}</div></section>`}).join('');bindKanban()}
function bindKanban(){$$('#kanbanView .kanban-card').forEach(card=>{card.ondragstart=e=>{e.dataTransfer.setData('text/plain',card.dataset.demandId);e.dataTransfer.effectAllowed='move';card.classList.add('dragging')};card.ondragend=()=>{$$('#kanbanView .kanban-column').forEach(c=>c.classList.remove('drag-over'));card.classList.remove('dragging')};card.onclick=e=>{if(!card.classList.contains('dragging'))openEdit(card.dataset.edit)}});$$('#kanbanView .kanban-column').forEach(column=>{column.ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect='move';column.classList.add('drag-over')};column.ondragleave=e=>{if(!column.contains(e.relatedTarget))column.classList.remove('drag-over')};column.ondrop=async e=>{e.preventDefault();column.classList.remove('drag-over');const id=e.dataTransfer.getData('text/plain'),d=demands.find(x=>x.id===id),status=column.dataset.dropStatus;if(!d||d.status===status)return;const previous=d.status;d.status=status;renderTable();const {error}=await db.from('demands').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error){d.status=previous;renderTable();toast('Não foi possível mover a demanda: '+error.message);return}toast(`Demanda movida para ${status}.`)}})}
function bindWorkspaceControls(){$$('[data-field]').forEach(x=>x.onchange=()=>updateDemand(x));$$('#tableView [data-edit]').forEach(x=>x.onclick=()=>openEdit(x.dataset.edit));$('#tableView').classList.toggle('hidden',viewMode!=='table');$('#kanbanView').classList.toggle('hidden',viewMode!=='kanban')}
async function updateDemand(el){el.disabled=true;const payload={[el.dataset.field]:el.value||null,updated_at:new Date().toISOString()};const {error}=await db.from('demands').update(payload).eq('id',el.dataset.id);el.disabled=false;if(error){toast('Erro ao atualizar: '+error.message);await loadDemands();return}const d=demands.find(x=>x.id===el.dataset.id);if(d)Object.assign(d,payload);renderTable();toast('Alteração salva.')}
function openEdit(id){const d=demands.find(x=>x.id===id);if(!d)return;const f=$('#editForm');Object.keys(d).forEach(k=>{if(f.elements[k])f.elements[k].value=d[k]??''});$('#editTitle').textContent=`${d.protocol} — Editar demanda`;const toggle=$('#toggleDemandActive');toggle.dataset.id=d.id;toggle.dataset.active=String(d.active!==false);toggle.textContent=d.active===false?'Reativar demanda':'Inativar demanda';toggle.classList.toggle('hidden',profile?.role!=='admin');$('#editModal').classList.remove('hidden');document.body.style.overflow='hidden'}
function closeEdit(){$('#editModal').classList.add('hidden');document.body.style.overflow=''}
$('#closeModal').onclick=closeEdit;$('#cancelEdit').onclick=closeEdit;$('#editModal').onclick=e=>{if(e.target===$('#editModal'))closeEdit()};
$('#toggleDemandActive').onclick=async e=>{const btn=e.currentTarget,id=btn.dataset.id,activate=btn.dataset.active==='false';if(!confirm(activate?'Reativar esta demanda?':'Inativar esta demanda? Ela sairá da visualização normal, mas continuará preservada.'))return;btn.disabled=true;const {error}=await db.rpc('set_demand_active',{p_id:id,p_active:activate});btn.disabled=false;if(error){toast('Não foi possível alterar a demanda: '+error.message);return}const d=demands.find(x=>x.id===id);if(d)d.active=activate;closeEdit();activeScope=activate?'all':'inactive';renderTable();toast(activate?'Demanda reativada.':'Demanda inativada.')};
$('#editForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const id=f.id;delete f.id;for(const k of ['email','assignee','notes'])f[k]=f[k]||null;f.updated_at=new Date().toISOString();const btn=e.currentTarget.querySelector('[type=submit]');btn.disabled=true;const {error}=await db.from('demands').update(f).eq('id',id);btn.disabled=false;if(error){toast('Erro ao salvar: '+error.message);return}const d=demands.find(x=>x.id===id);if(d)Object.assign(d,f);closeEdit();renderTable();toast('Demanda atualizada com sucesso.')};
function csvCell(v){return `"${String(v??'').replace(/"/g,'""')}"`}
function exportCsv(){const headers=['Protocolo','Data da solicitação','Solicitante','E-mail','Núcleo','Setor','Descrição','Resultado esperado','Prazo','Prioridade','Status','Responsável','Observações','Última atualização'];const rows=filtered().map(d=>[d.protocol,new Date(d.created_at).toLocaleDateString('pt-BR'),d.requester,d.email,d.nucleus,d.sector,d.description,d.expected_result,new Date(d.deadline+'T12:00:00').toLocaleDateString('pt-BR'),d.priority,d.status,d.assignee,d.notes,d.updated_at?new Date(d.updated_at).toLocaleString('pt-BR'):'']);const csv='\ufeff'+[headers,...rows].map(r=>r.map(csvCell).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`plano-de-acao-cdl-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
$('#exportButton').onclick=exportCsv;
let pendingImports=[];
$('#downloadImportModel').onclick=async e=>{e.preventDefault();const link=e.currentTarget,old=link.textContent;link.textContent='Preparando modelo...';try{const response=await fetch('modelo-importacao-demandas-cdl.base64',{cache:'no-store'});if(!response.ok)throw new Error('Modelo indisponível.');const binary=atob((await response.text()).trim());const bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const a=document.createElement('a');a.href=url;a.download='modelo-importacao-demandas-cdl.xlsx';a.click();URL.revokeObjectURL(url)}catch(error){toast(error.message)}finally{link.textContent=old}};
const normalizeHeader=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const canonical=(value,items)=>items.find(x=>normalizeHeader(x)===normalizeHeader(value));
function excelDate(value){if(value instanceof Date&&!isNaN(value))return `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,'0')}-${String(value.getDate()).padStart(2,'0')}`;if(typeof value==='number'){const p=XLSX.SSF.parse_date_code(value);if(p)return `${p.y}-${String(p.m).padStart(2,'0')}-${String(p.d).padStart(2,'0')}`}const s=String(value??'').trim();let m=s.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?s:''}
function closeImport(){$('#importModal').classList.add('hidden');document.body.style.overflow='';$('#importFile').value='';$('#importResult').className='import-result hidden';$('#confirmImport').disabled=true;pendingImports=[]}
$('#importButton').onclick=()=>{$('#importModal').classList.remove('hidden');document.body.style.overflow='hidden'};$('#closeImport').onclick=closeImport;$('#cancelImport').onclick=closeImport;$('#importModal').onclick=e=>{if(e.target===$('#importModal'))closeImport()};
$('#importFile').onchange=async e=>{const file=e.target.files[0],result=$('#importResult'),confirm=$('#confirmImport');pendingImports=[];confirm.disabled=true;if(!file)return;result.className='import-result';result.textContent='Validando arquivo...';try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});const ws=wb.Sheets['Demandas']||wb.Sheets[wb.SheetNames[0]];const raw=XLSX.utils.sheet_to_json(ws,{defval:'',raw:true});if(!raw.length)throw new Error('A planilha não contém demandas preenchidas.');if(raw.length>200)throw new Error('O limite é de 200 demandas por importação.');const errors=[];raw.forEach((source,i)=>{const row={};Object.entries(source).forEach(([k,v])=>row[normalizeHeader(k)]=v);if(Object.values(row).every(v=>String(v).trim()===''))return;const item={requester:String(row.solicitante??'').trim(),email:String(row.email??'').trim(),nucleus:canonical(row.nucleo,NUCLEI),sector:canonical(row.setor,SECTORS),description:String(row.descricao??'').trim(),expected_result:String(row.resultadoesperado??'').trim(),deadline:excelDate(row.prazo),priority:canonical(row.prioridade,PRIORITIES),status:canonical(row.status||'Não iniciado',STATUSES),assignee:String(row.responsavel??'').trim(),notes:String(row.observacoes??'').trim()};const missing=[];if(!item.requester)missing.push('Solicitante');if(!item.nucleus)missing.push('Núcleo inválido');if(!item.sector)missing.push('Setor inválido');if(!item.description)missing.push('Descrição');if(!item.expected_result)missing.push('Resultado esperado');if(!item.deadline)missing.push('Prazo inválido');if(!item.priority)missing.push('Prioridade inválida');if(!item.status)missing.push('Status inválido');if(item.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(item.email))missing.push('E-mail inválido');if(missing.length)errors.push(`Linha ${i+2}: ${missing.join(', ')}`);else pendingImports.push(item)});if(errors.length){pendingImports=[];result.className='import-result error';result.innerHTML=`<strong>O arquivo possui ${errors.length} ${errors.length===1?'linha com erro':'linhas com erros'}.</strong><p>Corrija o arquivo antes de importar. Nenhuma demanda foi gravada.</p><ul class="import-errors">${errors.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;return}if(!pendingImports.length)throw new Error('Nenhuma linha preenchida foi encontrada.');result.className='import-result success';result.innerHTML=`<strong>${pendingImports.length} ${pendingImports.length===1?'demanda válida':'demandas válidas'}.</strong><p>O arquivo está pronto para importação.</p>`;confirm.disabled=false}catch(error){result.className='import-result error';result.innerHTML=`<strong>Não foi possível validar o arquivo.</strong><p>${esc(error.message)}</p>`}};
$('#confirmImport').onclick=async()=>{const btn=$('#confirmImport'),result=$('#importResult');if(!pendingImports.length)return;btn.disabled=true;$('#cancelImport').disabled=true;let imported=0;const failures=[];for(let i=0;i<pendingImports.length;i++){const x=pendingImports[i];result.className='import-result';result.innerHTML=`<strong>Importando ${i+1} de ${pendingImports.length}...</strong><p>Não feche esta janela.</p>`;const {data:protocol,error}=await db.rpc('submit_demand',{p_requester:x.requester,p_email:x.email||null,p_nucleus:x.nucleus,p_sector:x.sector,p_description:x.description,p_expected_result:x.expected_result,p_deadline:x.deadline,p_priority:x.priority,p_notes:x.notes||null});if(error){failures.push(`Linha ${i+2}: ${error.message}`);continue}if(x.status!=='Não iniciado'||x.assignee){const {error:updateError}=await db.from('demands').update({status:x.status,assignee:x.assignee||null,updated_at:new Date().toISOString()}).eq('protocol',protocol);if(updateError)failures.push(`${protocol}: cadastrada, mas status/responsável não foram atualizados.`)}imported++}$('#cancelImport').disabled=false;pendingImports=[];if(failures.length){result.className='import-result error';result.innerHTML=`<strong>${imported} importadas; ${failures.length} com falha.</strong><ul class="import-errors">${failures.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`}else{result.className='import-result success';result.innerHTML=`<strong>${imported} ${imported===1?'demanda importada':'demandas importadas'} com sucesso.</strong><p>Todos os protocolos foram gerados e já estão no Plano de Ação.</p>`}await loadDemands()};
function count(field,rows=demands){return rows.reduce((a,d)=>(a[d[field]]=(a[d[field]]||0)+1,a),{})}
function bars(el,data){const max=Math.max(1,...Object.values(data));el.innerHTML=Object.entries(data).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div><div class="bar-head"><span>${esc(k)}</span><strong>${v}</strong></div><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div></div>`).join('')||'<p>Sem dados.</p>'}
function renderDashboard(){const rows=demands.filter(d=>d.active!==false),today=new Date().toISOString().slice(0,10),open=rows.filter(d=>!['Concluído','Cancelado'].includes(d.status)),late=open.filter(d=>d.deadline<today);$('#kpis').innerHTML=[['Total',rows.length],['Em aberto',open.length],['Atrasadas',late.length],['Concluídas',rows.filter(d=>d.status==='Concluído').length]].map(([k,v])=>`<div class="kpi"><strong>${v}</strong><span>${k}</span></div>`).join('');bars($('#statusChart'),count('status',rows));bars($('#nucleusChart'),count('nucleus',rows));$('#deadlines').innerHTML=open.slice(0,8).map(d=>`<div class="deadline-item"><strong>${new Date(d.deadline+'T12:00:00').toLocaleDateString('pt-BR')}</strong><span>${esc(d.description)}</span><span class="badge ${priorityClass(d.priority)}">${esc(d.priority)}</span></div>`).join('')||'<p>Sem demandas abertas.</p>'}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),3000)}
function notificationKey(suffix){return `cdl_notifications_${session?.user?.id||'guest'}_${suffix}`}
function startNotifications(){if(!session||!profile)return;stopNotifications();notifications=JSON.parse(localStorage.getItem(notificationKey('items'))||'[]');soundEnabled=localStorage.getItem(notificationKey('sound'))==='on';renderNotifications();pollNotifications(true);notificationTimer=setInterval(()=>pollNotifications(false),30000)}
function stopNotifications(){if(notificationTimer)clearInterval(notificationTimer);notificationTimer=null;$('#notificationPanel')?.classList.add('hidden')}
async function pollNotifications(initial=false){if(!session||!profile)return;let since=localStorage.getItem(notificationKey('since'));if(!since){localStorage.setItem(notificationKey('since'),new Date().toISOString());return}if(profile.role!=='admin'&&!profile.sector){localStorage.setItem(notificationKey('since'),new Date().toISOString());return}const found=[];let q=db.from('demands').select('id,protocol,requester,sector,description,created_at').gt('created_at',since).order('created_at',{ascending:true});if(profile.role!=='admin')q=q.eq('sector',profile.sector);const {data:demandRows}=await q;for(const d of demandRows||[])found.push({id:`d-${d.id}`,type:'demand',code:d.protocol,title:`Nova demanda para ${d.sector}`,text:`${d.requester}: ${d.description}`,created_at:d.created_at,read:false});if(profile.role==='admin'){const {data:ideaRows}=await db.from('ideas').select('id,code,author,title,created_at').gt('created_at',since).order('created_at',{ascending:true});for(const i of ideaRows||[])found.push({id:`i-${i.id}`,type:'idea',code:i.code,title:'Nova ideia cadastrada',text:`${i.author}: ${i.title}`,created_at:i.created_at,read:false})}localStorage.setItem(notificationKey('since'),new Date().toISOString());const existing=new Set(notifications.map(n=>n.id)),fresh=found.filter(n=>!existing.has(n.id));if(!fresh.length)return;notifications=[...fresh.reverse(),...notifications].slice(0,40);saveNotifications();renderNotifications();if(!initial&&soundEnabled)playNotificationSound()}
function saveNotifications(){localStorage.setItem(notificationKey('items'),JSON.stringify(notifications))}
function renderNotifications(){const unread=notifications.filter(n=>!n.read).length,badge=$('#notificationBadge');badge.textContent=unread>99?'99+':unread;badge.classList.toggle('hidden',!unread);$('#soundToggle').textContent=soundEnabled?'🔊 Som ativado':'🔇 Ativar som';$('#notificationList').innerHTML=notifications.length?notifications.map(n=>`<button class="notification-item ${n.read?'':'unread'}" data-notification="${esc(n.id)}"><strong>${esc(n.title)}</strong><span>${esc(n.code)} — ${esc(n.text)}</span><small>${new Date(n.created_at).toLocaleString('pt-BR')}</small></button>`).join(''):'<div class="notification-empty">Nenhuma notificação nova.</div>';$$('[data-notification]').forEach(b=>b.onclick=()=>openNotification(b.dataset.notification))}
function openNotification(id){const n=notifications.find(x=>x.id===id);if(!n)return;n.read=true;saveNotifications();renderNotifications();$('#notificationPanel').classList.add('hidden');location.hash=n.type==='idea'?'#/ideias':'#/plano';setTimeout(()=>{const input=n.type==='idea'?$('#ideaSearch'):$('#search');if(input){input.value=n.code;input.dispatchEvent(new Event('input'))}},500)}
function playNotificationSound(){try{const AudioContext=window.AudioContext||window.webkitAudioContext,ctx=new AudioContext(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.frequency.setValueAtTime(880,ctx.currentTime);gain.gain.setValueAtTime(.08,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.35);osc.start();osc.stop(ctx.currentTime+.35)}catch(_e){}}
$('#notificationBell').onclick=e=>{e.stopPropagation();$('#notificationPanel').classList.toggle('hidden')};$('#notificationPanel').onclick=e=>e.stopPropagation();document.addEventListener('click',()=>$('#notificationPanel').classList.add('hidden'));$('#markAllRead').onclick=()=>{notifications.forEach(n=>n.read=true);saveNotifications();renderNotifications()};$('#soundToggle').onclick=()=>{soundEnabled=!soundEnabled;localStorage.setItem(notificationKey('sound'),soundEnabled?'on':'off');renderNotifications();if(soundEnabled)playNotificationSound()};
['search','filterStatus','filterNucleus','filterSector','filterPriority'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',renderTable));$('#refreshButton').onclick=()=>loadWorkspace();
$$('#scopeTabs button').forEach(b=>b.onclick=()=>{if(b.disabled)return;if(b.dataset.scope==='all')clearDemandFilters();activeScope=b.dataset.scope;renderTable()});
$$('.view-switch button').forEach(b=>b.onclick=()=>{viewMode=b.dataset.mode;$$('.view-switch button').forEach(x=>x.classList.toggle('active',x===b));renderTable()});
$('#refreshProfiles').onclick=loadProfiles;
(async()=>{if(configured){const {data}=await db.auth.getSession();session=data.session;if(session)await loadProfile();db.auth.onAuthStateChange(async(_e,s)=>{session=s;if(s)await loadProfile();else stopNotifications();setAuthUI()})}setAuthUI();route()})();
