const C=window.CDL_CONFIG||{};
const configured=Boolean(C.supabaseUrl&&C.supabaseAnonKey);
const db=configured?window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey):null;
const NUCLEI=['CDL Mulher','CDL Jovem','CDL Innova','CDL Cultura','Caminhos de Hamburgo Velho','Conselho','Diretoria','Outro'];
const SECTORS=['Marketing e Comunicação','Comercial','Relacionamento e Atendimento','Financeiro e Administrativo','TI, CRM e Automação','Eventos','Gestão Executiva','Presidência e Conselho','Outro'];
const PRIORITIES=['Urgente','Alta','Média','Baixa'];
const STATUSES=['Não iniciado','Em andamento','Aguardando retorno','Concluído','Cancelado'];
let session=null, demands=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fillSelect(el,items,first='Selecione'){el.innerHTML=`<option value="">${first}</option>`+items.map(v=>`<option>${esc(v)}</option>`).join('')}
fillSelect($('[name=nucleus]'),NUCLEI);fillSelect($('[name=sector]'),SECTORS);fillSelect($('[name=priority]'),PRIORITIES);$('[name=priority]').value='Média';
fillSelect($('#filterStatus'),STATUSES,'Todos os status');fillSelect($('#filterNucleus'),NUCLEI,'Todos os núcleos');fillSelect($('#filterPriority'),PRIORITIES,'Todas as prioridades');
function route(){const id=location.hash.replace('#/','')||'nova';$$('.view').forEach(v=>v.classList.add('hidden'));if(!configured){$('#setup').classList.remove('hidden');return}const protectedView=['plano','dashboard'].includes(id);if(protectedView&&!session){location.hash='#/login';return}$('#'+(document.getElementById(id)?id:'nova')).classList.remove('hidden');if(id==='plano')loadDemands();if(id==='dashboard')loadDemands(true)}
function setAuthUI(){ $$('.admin-only').forEach(x=>x.classList.toggle('hidden',!session));$('#authButton').textContent=session?'Sair':'Área administrativa'}
window.addEventListener('hashchange',route);
$('#authButton').onclick=async()=>{if(session){await db.auth.signOut();session=null;setAuthUI();location.hash='#/nova'}else location.hash='#/login'};
$('#demandForm').onsubmit=async e=>{e.preventDefault();const btn=$('#sendButton'),msg=$('#formMessage');btn.disabled=true;msg.className='message';msg.textContent='Registrando...';const f=Object.fromEntries(new FormData(e.currentTarget));const {data,error}=await db.rpc('submit_demand',{p_requester:f.requester,p_email:f.email||null,p_nucleus:f.nucleus,p_sector:f.sector,p_description:f.description,p_expected_result:f.expected_result,p_deadline:f.deadline,p_priority:f.priority,p_notes:f.notes||null});btn.disabled=false;if(error){msg.classList.add('error');msg.textContent='Não foi possível registrar. '+error.message;return}msg.classList.add('success');msg.textContent=`Demanda registrada com sucesso. Protocolo ${data}.`;e.currentTarget.reset();$('[name=priority]').value='Média'};
$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),msg=$('#loginMessage');msg.textContent='Entrando...';const {data,error}=await db.auth.signInWithPassword({email:f.email,password:f.password});if(error){msg.className='message error';msg.textContent='E-mail ou senha inválidos.';return}session=data.session;setAuthUI();location.hash='#/plano'};
async function loadDemands(toDashboard=false){const {data,error}=await db.from('demands').select('*').order('deadline',{ascending:true});if(error){toast(error.message);return}demands=data||[];if(toDashboard)renderDashboard();else renderTable()}
function filtered(){const q=$('#search').value.toLowerCase(),s=$('#filterStatus').value,n=$('#filterNucleus').value,p=$('#filterPriority').value;return demands.filter(d=>(!q||`${d.protocol} ${d.description} ${d.requester}`.toLowerCase().includes(q))&&(!s||d.status===s)&&(!n||d.nucleus===n)&&(!p||d.priority===p))}
function options(items,current){return items.map(x=>`<option ${x===current?'selected':''}>${esc(x)}</option>`).join('')}
function priorityClass(p){return {Urgente:'urgent',Alta:'high','Média':'medium',Baixa:'low'}[p]||'low'}
function renderTable(){const rows=filtered();$('#emptyTable').classList.toggle('hidden',rows.length>0);$('#demandRows').innerHTML=rows.map(d=>`<tr><td><strong>${esc(d.protocol)}</strong><br><small>${new Date(d.created_at).toLocaleDateString('pt-BR')}</small></td><td>${new Date(d.deadline+'T12:00:00').toLocaleDateString('pt-BR')}</td><td><strong>${esc(d.description)}</strong><br><small>${esc(d.requester)}</small></td><td>${esc(d.nucleus)}</td><td>${esc(d.sector)}</td><td><span class="badge ${priorityClass(d.priority)}">${esc(d.priority)}</span></td><td><select data-id="${d.id}" data-field="status">${options(STATUSES,d.status)}</select></td><td><input data-id="${d.id}" data-field="assignee" value="${esc(d.assignee||'')}" placeholder="Definir responsável"></td></tr>`).join('');$$('[data-field=status]').forEach(x=>x.onchange=()=>updateDemand(x));$$('[data-field=assignee]').forEach(x=>x.onchange=()=>updateDemand(x))}
async function updateDemand(el){const {error}=await db.from('demands').update({[el.dataset.field]:el.value||null}).eq('id',el.dataset.id);toast(error?'Erro ao atualizar: '+error.message:'Demanda atualizada.')}
function count(field){return demands.reduce((a,d)=>(a[d[field]]=(a[d[field]]||0)+1,a),{})}
function bars(el,data){const max=Math.max(1,...Object.values(data));el.innerHTML=Object.entries(data).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div><div class="bar-head"><span>${esc(k)}</span><strong>${v}</strong></div><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div></div>`).join('')||'<p>Sem dados.</p>'}
function renderDashboard(){const today=new Date().toISOString().slice(0,10),open=demands.filter(d=>!['Concluído','Cancelado'].includes(d.status)),late=open.filter(d=>d.deadline<today);$('#kpis').innerHTML=[['Total',demands.length],['Em aberto',open.length],['Atrasadas',late.length],['Concluídas',demands.filter(d=>d.status==='Concluído').length]].map(([k,v])=>`<div class="kpi"><strong>${v}</strong><span>${k}</span></div>`).join('');bars($('#statusChart'),count('status'));bars($('#nucleusChart'),count('nucleus'));$('#deadlines').innerHTML=open.slice(0,8).map(d=>`<div class="deadline-item"><strong>${new Date(d.deadline+'T12:00:00').toLocaleDateString('pt-BR')}</strong><span>${esc(d.description)}</span><span class="badge ${priorityClass(d.priority)}">${esc(d.priority)}</span></div>`).join('')||'<p>Sem demandas abertas.</p>'}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),3000)}
['search','filterStatus','filterNucleus','filterPriority'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',renderTable));$('#refreshButton').onclick=()=>loadDemands();
(async()=>{if(configured){const {data}=await db.auth.getSession();session=data.session;db.auth.onAuthStateChange((_e,s)=>{session=s;setAuthUI()})}setAuthUI();route()})();
