const C=window.CDL_CONFIG||{};
const configured=Boolean(C.supabaseUrl&&C.supabaseAnonKey);
const db=configured?window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey):null;
const NUCLEI=['CDL Mulher','CDL Jovem','CDL Innova','CDL Cultura','Caminhos de Hamburgo Velho','Conselho','Diretoria','Outro'];
const SECTORS=['Marketing e Comunicação','Comercial','Relacionamento e Atendimento','Financeiro e Administrativo','TI, CRM e Automação','Eventos','Gestão Executiva','Presidência e Conselho','Outro'];
const PRIORITIES=['Urgente','Alta','Média','Baixa'];
const STATUSES=['Não iniciado','Em andamento','Aguardando retorno','Concluído','Cancelado'];
let session=null, demands=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fillSelect(el,items,first='Selecione'){el.innerHTML=`<option value="">${first}</option>`+items.map(v=>`<option>${esc(v)}</option>`).join('')}
fillSelect($('[name=nucleus]'),NUCLEI);fillSelect($('[name=sector]'),SECTORS);fillSelect($('[name=priority]'),PRIORITIES);$('[name=priority]').value='Média';
fillSelect($('#filterStatus'),STATUSES,'Todos os status');fillSelect($('#filterNucleus'),NUCLEI,'Todos os núcleos');fillSelect($('#filterPriority'),PRIORITIES,'Todas as prioridades');
fillSelect($('#filterSector'),SECTORS,'Todos os setores');
fillSelect($('#editForm [name=nucleus]'),NUCLEI);fillSelect($('#editForm [name=sector]'),SECTORS);fillSelect($('#editForm [name=priority]'),PRIORITIES);fillSelect($('#editForm [name=status]'),STATUSES);
function route(){const id=location.hash.replace('#/','')||'nova';$$('.view').forEach(v=>v.classList.add('hidden'));if(!configured){$('#setup').classList.remove('hidden');return}const protectedView=['plano','dashboard'].includes(id);if(protectedView&&!session){location.hash='#/login';return}$('#'+(document.getElementById(id)?id:'nova')).classList.remove('hidden');if(id==='plano')loadDemands();if(id==='dashboard')loadDemands(true)}
function setAuthUI(){ $$('.admin-only').forEach(x=>x.classList.toggle('hidden',!session));$('#authButton').textContent=session?'Sair':'Área administrativa'}
window.addEventListener('hashchange',route);
$('#authButton').onclick=async()=>{if(session){await db.auth.signOut();session=null;setAuthUI();location.hash='#/nova'}else location.hash='#/login'};
$('#demandForm').onsubmit=async e=>{e.preventDefault();const btn=$('#sendButton'),msg=$('#formMessage');btn.disabled=true;msg.className='message';msg.textContent='Registrando...';const f=Object.fromEntries(new FormData(e.currentTarget));const {data,error}=await db.rpc('submit_demand',{p_requester:f.requester,p_email:f.email||null,p_nucleus:f.nucleus,p_sector:f.sector,p_description:f.description,p_expected_result:f.expected_result,p_deadline:f.deadline,p_priority:f.priority,p_notes:f.notes||null});btn.disabled=false;if(error){msg.classList.add('error');msg.textContent='Não foi possível registrar. '+error.message;return}msg.classList.add('success');msg.textContent=`Demanda registrada com sucesso. Protocolo ${data}.`;e.currentTarget.reset();$('[name=priority]').value='Média'};
$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),msg=$('#loginMessage');msg.textContent='Entrando...';const {data,error}=await db.auth.signInWithPassword({email:f.email,password:f.password});if(error){msg.className='message error';msg.textContent='E-mail ou senha inválidos.';return}session=data.session;setAuthUI();location.hash='#/plano'};
async function loadDemands(toDashboard=false){const {data,error}=await db.from('demands').select('*').order('deadline',{ascending:true});if(error){toast(error.message);return}demands=data||[];if(toDashboard)renderDashboard();else renderTable()}
function filtered(){const q=$('#search').value.toLowerCase(),s=$('#filterStatus').value,n=$('#filterNucleus').value,t=$('#filterSector').value,p=$('#filterPriority').value;return demands.filter(d=>(!q||`${d.protocol} ${d.description} ${d.requester} ${d.assignee||''} ${d.notes||''}`.toLowerCase().includes(q))&&(!s||d.status===s)&&(!n||d.nucleus===n)&&(!t||d.sector===t)&&(!p||d.priority===p))}
function options(items,current){return items.map(x=>`<option ${x===current?'selected':''}>${esc(x)}</option>`).join('')}
function priorityClass(p){return {Urgente:'urgent',Alta:'high','Média':'medium',Baixa:'low'}[p]||'low'}
function renderTable(){const rows=filtered();$('#resultCount').textContent=`${rows.length} ${rows.length===1?'demanda':'demandas'}`;$('#emptyTable').classList.toggle('hidden',rows.length>0);$('#demandRows').innerHTML=rows.map(d=>`<tr><td><strong>${esc(d.protocol)}</strong></td><td><strong>${new Date(d.created_at).toLocaleDateString('pt-BR')}</strong><br><small>${esc(d.requester)}</small></td><td><input class="date-input" type="date" data-id="${d.id}" data-field="deadline" value="${esc(d.deadline)}"></td><td class="demand-cell"><strong title="${esc(d.description)}">${esc(d.description)}</strong><br><small>Resultado: ${esc(d.expected_result)}</small></td><td class="meta-cell"><strong>${esc(d.nucleus)}</strong><br><small>${esc(d.sector)}</small></td><td><select data-id="${d.id}" data-field="priority">${options(PRIORITIES,d.priority)}</select></td><td><select data-id="${d.id}" data-field="status">${options(STATUSES,d.status)}</select></td><td><input data-id="${d.id}" data-field="assignee" value="${esc(d.assignee||'')}" placeholder="Definir responsável"></td><td class="meta-cell"><span class="notes-preview" title="${esc(d.notes||'')}">${esc(d.notes||'Sem observações')}</span></td><td><button class="row-action" data-edit="${d.id}">Abrir</button></td></tr>`).join('');$$('[data-field]').forEach(x=>x.onchange=()=>updateDemand(x));$$('[data-edit]').forEach(x=>x.onclick=()=>openEdit(x.dataset.edit))}
async function updateDemand(el){el.disabled=true;const payload={[el.dataset.field]:el.value||null,updated_at:new Date().toISOString()};const {error}=await db.from('demands').update(payload).eq('id',el.dataset.id);el.disabled=false;if(error){toast('Erro ao atualizar: '+error.message);await loadDemands();return}const d=demands.find(x=>x.id===el.dataset.id);if(d)Object.assign(d,payload);toast('Alteração salva.')}
function openEdit(id){const d=demands.find(x=>x.id===id);if(!d)return;const f=$('#editForm');Object.keys(d).forEach(k=>{if(f.elements[k])f.elements[k].value=d[k]??''});$('#editTitle').textContent=`${d.protocol} — Editar demanda`;$('#editModal').classList.remove('hidden');document.body.style.overflow='hidden'}
function closeEdit(){$('#editModal').classList.add('hidden');document.body.style.overflow=''}
$('#closeModal').onclick=closeEdit;$('#cancelEdit').onclick=closeEdit;$('#editModal').onclick=e=>{if(e.target===$('#editModal'))closeEdit()};
$('#editForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const id=f.id;delete f.id;for(const k of ['email','assignee','notes'])f[k]=f[k]||null;f.updated_at=new Date().toISOString();const btn=e.currentTarget.querySelector('[type=submit]');btn.disabled=true;const {error}=await db.from('demands').update(f).eq('id',id);btn.disabled=false;if(error){toast('Erro ao salvar: '+error.message);return}const d=demands.find(x=>x.id===id);if(d)Object.assign(d,f);closeEdit();renderTable();toast('Demanda atualizada com sucesso.')};
function csvCell(v){return `"${String(v??'').replace(/"/g,'""')}"`}
function exportCsv(){const headers=['Protocolo','Data da solicitação','Solicitante','E-mail','Núcleo','Setor','Descrição','Resultado esperado','Prazo','Prioridade','Status','Responsável','Observações','Última atualização'];const rows=filtered().map(d=>[d.protocol,new Date(d.created_at).toLocaleDateString('pt-BR'),d.requester,d.email,d.nucleus,d.sector,d.description,d.expected_result,new Date(d.deadline+'T12:00:00').toLocaleDateString('pt-BR'),d.priority,d.status,d.assignee,d.notes,d.updated_at?new Date(d.updated_at).toLocaleString('pt-BR'):'']);const csv='\ufeff'+[headers,...rows].map(r=>r.map(csvCell).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`plano-de-acao-cdl-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
$('#exportButton').onclick=exportCsv;
function count(field){return demands.reduce((a,d)=>(a[d[field]]=(a[d[field]]||0)+1,a),{})}
function bars(el,data){const max=Math.max(1,...Object.values(data));el.innerHTML=Object.entries(data).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div><div class="bar-head"><span>${esc(k)}</span><strong>${v}</strong></div><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div></div>`).join('')||'<p>Sem dados.</p>'}
function renderDashboard(){const today=new Date().toISOString().slice(0,10),open=demands.filter(d=>!['Concluído','Cancelado'].includes(d.status)),late=open.filter(d=>d.deadline<today);$('#kpis').innerHTML=[['Total',demands.length],['Em aberto',open.length],['Atrasadas',late.length],['Concluídas',demands.filter(d=>d.status==='Concluído').length]].map(([k,v])=>`<div class="kpi"><strong>${v}</strong><span>${k}</span></div>`).join('');bars($('#statusChart'),count('status'));bars($('#nucleusChart'),count('nucleus'));$('#deadlines').innerHTML=open.slice(0,8).map(d=>`<div class="deadline-item"><strong>${new Date(d.deadline+'T12:00:00').toLocaleDateString('pt-BR')}</strong><span>${esc(d.description)}</span><span class="badge ${priorityClass(d.priority)}">${esc(d.priority)}</span></div>`).join('')||'<p>Sem demandas abertas.</p>'}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),3000)}
['search','filterStatus','filterNucleus','filterSector','filterPriority'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',renderTable));$('#refreshButton').onclick=()=>loadDemands();
(async()=>{if(configured){const {data}=await db.auth.getSession();session=data.session;db.auth.onAuthStateChange((_e,s)=>{session=s;setAuthUI()})}setAuthUI();route()})();
