const IDEA_ORIGINS=[...new Set([...NUCLEI,...SECTORS,'Gestão da CDL','Associado','Outro'])];
const IDEA_THEMES=['Novos serviços','Eventos','Inovação e tecnologia','Relacionamento com associados','Desenvolvimento empresarial','Comunicação e marca','Receita e sustentabilidade','Eficiência interna','Desenvolvimento da cidade','Outro'];
const IDEA_STAGES=['Nova','Em triagem','Em análise','Priorizada','Em desenvolvimento','Transformada em projeto','Relacionada ou duplicada','Arquivada'];
let ideas=[],ideaStage='all',ideaMode='table';

fillSelect($('#ideaForm [name=origin]'),IDEA_ORIGINS);
fillSelect($('#ideaForm [name=theme]'),IDEA_THEMES);
fillSelect($('#ideaEditForm [name=origin]'),IDEA_ORIGINS);
fillSelect($('#ideaEditForm [name=theme]'),IDEA_THEMES);
fillSelect($('#ideaEditForm [name=stage]'),IDEA_STAGES);
fillSelect($('#ideaOriginFilter'),IDEA_ORIGINS,'Todas as origens');
fillSelect($('#ideaThemeFilter'),IDEA_THEMES,'Todos os temas');

$('#ideaForm').onsubmit=async e=>{e.preventDefault();const btn=$('#sendIdeaButton'),msg=$('#ideaFormMessage'),f=Object.fromEntries(new FormData(e.currentTarget));btn.disabled=true;msg.className='message';msg.textContent='Registrando ideia...';const {data,error}=await db.rpc('submit_idea',{p_author:f.author,p_email:f.email||null,p_origin:f.origin,p_theme:f.theme,p_title:f.title,p_problem:f.problem,p_description:f.description,p_beneficiaries:f.beneficiaries,p_expected_benefit:f.expected_benefit,p_similar_initiative:f.similar_initiative||null,p_partners:f.partners||null,p_references:f.references||null});btn.disabled=false;if(error){msg.classList.add('error');msg.textContent=error.message.includes('submit_idea')?'O Banco de Ideias ainda precisa ser ativado no Supabase.':'Não foi possível registrar. '+error.message;return}msg.classList.add('success');msg.textContent=`Ideia registrada com sucesso. Código ${data}.`;e.currentTarget.reset()};

async function loadIdeas(){const query=profile?.role==='admin'?db.rpc('list_admin_ideas'):db.from('ideas').select('*').order('created_at',{ascending:false});const {data,error}=await query;if(error){ideas=[];renderIdeas();toast('Não foi possível carregar o Banco de Ideias: '+error.message);return}ideas=(data||[]).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)));renderIdeas()}
function ideaScore(x){return Number((Number(x.score_alignment||0)*.25+Number(x.score_impact||0)*.25+Number(x.score_reach||0)*.10+Number(x.score_synergy||0)*.15+Number(x.score_feasibility||0)*.15+Number(x.score_urgency||0)*.10).toFixed(1))}
function ideaFiltered(){const q=$('#ideaSearch').value.toLowerCase(),o=$('#ideaOriginFilter').value,t=$('#ideaThemeFilter').value;return ideas.filter(x=>{const isActive=x.active!==false,visible=ideaStage==='inactive'?profile?.role==='admin'&&!isActive:isActive&&(ideaStage==='all'||x.stage===ideaStage);return visible&&(!o||x.origin===o)&&(!t||x.theme===t)&&(!q||`${x.code} ${x.title} ${x.author} ${x.problem} ${x.description} ${x.expected_benefit}`.toLowerCase().includes(q))})}
function ideaStageSlug(s){return normalizeHeader(s)||'nova'}
function renderIdeaTabs(){const activeIdeas=ideas.filter(x=>x.active!==false),inactive=ideas.filter(x=>x.active===false);$('#ideaStageTabs').innerHTML=`<button data-idea-stage="all" class="${ideaStage==='all'?'active':''}">Todas <span>${activeIdeas.length}</span></button>`+IDEA_STAGES.map(s=>`<button data-idea-stage="${esc(s)}" class="${ideaStage===s?'active':''}">${esc(s)} <span>${activeIdeas.filter(x=>x.stage===s).length}</span></button>`).join('')+(profile?.role==='admin'?`<button data-idea-stage="inactive" class="${ideaStage==='inactive'?'active':''}">Inativas <span>${inactive.length}</span></button>`:'');$$('[data-idea-stage]').forEach(b=>b.onclick=()=>{ideaStage=b.dataset.ideaStage;renderIdeas()})}
function renderIdeas(){const rows=ideaFiltered();renderIdeaTabs();$('#ideaResultCount').textContent=`${rows.length} ${rows.length===1?'ideia':'ideias'}`;$('#ideaViewHint').textContent=ideaMode==='kanban'?'Arraste a ideia entre as etapas para atualizar sua situação.':'Clique em uma ideia para avaliar, relacionar e transformar em projeto.';$('#emptyIdeas').classList.toggle('hidden',rows.length>0);$('#ideaRows').innerHTML=rows.map(x=>`<tr><td><strong>${esc(x.code)}</strong><br><small>${new Date(x.created_at).toLocaleDateString('pt-BR')}</small></td><td class="idea-title-cell"><strong>${esc(x.title)}</strong><small>${esc(x.author)} · ${esc(x.expected_benefit)}</small></td><td>${esc(x.origin)}</td><td>${esc(x.theme)}</td><td><span class="idea-stage-badge ${ideaStageSlug(x.stage)}">${esc(x.stage)}</span></td><td><strong class="score-pill">${ideaScore(x).toFixed(1)}</strong></td><td><button class="row-action" data-idea-edit="${x.id}">Abrir</button></td></tr>`).join('');renderIdeaKanban(rows);$$('[data-idea-edit]').forEach(b=>b.onclick=()=>openIdea(b.dataset.ideaEdit));$('#ideaTableView').classList.toggle('hidden',ideaMode!=='table');$('#ideaKanbanView').classList.toggle('hidden',ideaMode!=='kanban')}
function renderIdeaKanban(rows){$('#ideaKanbanView').innerHTML=IDEA_STAGES.map(stage=>{const cards=rows.filter(x=>x.stage===stage);return `<section class="idea-column ${ideaStageSlug(stage)}" data-idea-drop="${esc(stage)}"><header><strong>${esc(stage)}</strong><span>${cards.length}</span></header><div class="idea-dropzone">${cards.map(x=>`<article class="idea-card summary-card" draggable="true" data-idea-id="${x.id}" data-idea-edit="${x.id}"><div><strong>${esc(x.code)}</strong><span class="score-pill">${ideaScore(x).toFixed(1)}</span></div><dl><div><dt>Quem cadastrou</dt><dd>${esc(x.author)}</dd></div><div><dt>Finalidade</dt><dd class="summary-purpose" title="${esc(x.expected_benefit)}">${esc(x.expected_benefit)}</dd></div><div><dt>Responsável</dt><dd>${esc(x.reviewer||'Não definido')}</dd></div><div><dt>Data de registro</dt><dd>${new Date(x.created_at).toLocaleDateString('pt-BR')}</dd></div><div><dt>Status</dt><dd>${esc(x.stage)}</dd></div></dl></article>`).join('')||'<p class="column-empty">Solte uma ideia aqui</p>'}</div></section>`}).join('');bindIdeaKanban()}
function bindIdeaKanban(){$$('#ideaKanbanView .idea-card').forEach(card=>{card.ondragstart=e=>{e.dataTransfer.setData('text/plain',card.dataset.ideaId);card.classList.add('dragging')};card.ondragend=()=>{card.classList.remove('dragging');$$('.idea-column').forEach(c=>c.classList.remove('drag-over'))};card.onclick=()=>openIdea(card.dataset.ideaEdit)});$$('[data-idea-drop]').forEach(col=>{col.ondragover=e=>{e.preventDefault();col.classList.add('drag-over')};col.ondragleave=e=>{if(!col.contains(e.relatedTarget))col.classList.remove('drag-over')};col.ondrop=async e=>{e.preventDefault();col.classList.remove('drag-over');const id=e.dataTransfer.getData('text/plain'),x=ideas.find(i=>i.id===id),stage=col.dataset.ideaDrop;if(!x||x.stage===stage)return;const old=x.stage;x.stage=stage;renderIdeas();const {error}=await db.from('ideas').update({stage,updated_at:new Date().toISOString()}).eq('id',id);if(error){x.stage=old;renderIdeas();toast('Não foi possível mover a ideia.');return}toast(`Ideia movida para ${stage}.`)}})}
function relatedOptions(currentId,current){return '<option value="">Nenhuma ideia relacionada</option>'+ideas.filter(x=>x.id!==currentId).map(x=>`<option value="${x.id}" ${x.id===current?'selected':''}>${esc(x.code)} — ${esc(x.title)}</option>`).join('')}
function openIdea(id){const x=ideas.find(i=>i.id===id);if(!x)return;const f=$('#ideaEditForm');Object.keys(x).forEach(k=>{if(f.elements[k])f.elements[k].value=x[k]??''});f.elements.related_idea_id.innerHTML=relatedOptions(id,x.related_idea_id);$('#ideaEditTitle').textContent=`${x.code} — ${x.title}`;const toggle=$('#toggleIdeaActive');toggle.dataset.id=x.id;toggle.dataset.active=String(x.active!==false);toggle.textContent=x.active===false?'Reativar ideia':'Inativar ideia';toggle.classList.toggle('hidden',profile?.role!=='admin');updateIdeaScorePreview();$('#ideaModal').classList.remove('hidden');document.body.style.overflow='hidden'}
function closeIdea(){$('#ideaModal').classList.add('hidden');document.body.style.overflow=''}
function updateIdeaScorePreview(){const f=$('#ideaEditForm'),value=ideaScore(Object.fromEntries(new FormData(f)));$('#ideaScorePreview').textContent=`Pontuação: ${value.toFixed(1)} de 5,0`}
$('#closeIdeaModal').onclick=closeIdea;$('#cancelIdeaEdit').onclick=closeIdea;$('#ideaModal').onclick=e=>{if(e.target===$('#ideaModal'))closeIdea()};$$('#ideaEditForm [name^=score_]').forEach(x=>x.oninput=updateIdeaScorePreview);
$('#toggleIdeaActive').onclick=async e=>{const btn=e.currentTarget,id=btn.dataset.id,activate=btn.dataset.active==='false',question=activate?'Reativar esta ideia?':'Inativar esta ideia? Ela deixará de aparecer para gestores e colaboradores.';if(!confirm(question))return;btn.disabled=true;const {error}=await db.rpc('set_idea_active',{p_id:id,p_active:activate});btn.disabled=false;if(error){toast('Não foi possível alterar a ideia: '+error.message);return}const x=ideas.find(v=>v.id===id);if(x)x.active=activate;closeIdea();ideaStage=activate?'all':'inactive';renderIdeas();toast(activate?'Ideia reativada.':'Ideia inativada e ocultada dos demais perfis.')};
$('#ideaEditForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),id=f.id;delete f.id;for(const k of ['score_alignment','score_impact','score_reach','score_synergy','score_feasibility','score_urgency'])f[k]=Math.max(0,Math.min(5,Number(f[k]||0)));for(const k of ['email','reviewer','similar_initiative','partners','reference_notes','related_idea_id','project_name','management_notes'])f[k]=f[k]||null;f.priority_score=ideaScore(f);f.updated_at=new Date().toISOString();const btn=e.currentTarget.querySelector('[type=submit]');btn.disabled=true;const {error}=await db.from('ideas').update(f).eq('id',id);btn.disabled=false;if(error){toast('Erro ao salvar: '+error.message);return}const x=ideas.find(i=>i.id===id);if(x)Object.assign(x,f);closeIdea();renderIdeas();toast('Análise da ideia salva.')};
$('#convertIdeaButton').onclick=()=>{const f=$('#ideaEditForm');if(!f.elements.project_name.value.trim()){toast('Informe primeiro o nome do projeto.');f.elements.project_name.focus();return}f.elements.stage.value='Transformada em projeto';f.requestSubmit()};
function exportIdeas(){const headers=['Código','Data','Autor','E-mail','Origem','Tema','Título','Problema ou oportunidade','Descrição','Público beneficiado','Benefício esperado','Etapa','Pontuação','Responsável pela análise','Projeto','Parecer'];const rows=ideaFiltered().map(x=>[x.code,new Date(x.created_at).toLocaleDateString('pt-BR'),x.author,x.email,x.origin,x.theme,x.title,x.problem,x.description,x.beneficiaries,x.expected_benefit,x.stage,ideaScore(x),x.reviewer,x.project_name,x.management_notes]);const csv='\ufeff'+[headers,...rows].map(r=>r.map(csvCell).join(';')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`banco-de-ideias-cdl-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
['ideaSearch','ideaOriginFilter','ideaThemeFilter'].forEach(id=>$('#'+id).addEventListener(id==='ideaSearch'?'input':'change',renderIdeas));
$$('[data-idea-mode]').forEach(b=>b.onclick=()=>{ideaMode=b.dataset.ideaMode;$$('[data-idea-mode]').forEach(x=>x.classList.toggle('active',x===b));renderIdeas()});
$('#refreshIdeasButton').onclick=loadIdeas;$('#exportIdeasButton').onclick=exportIdeas;
if(location.hash==='#/ideias'&&session)loadIdeas();
