const sb=window.supabase.createClient(window.CDL_CONFIG.supabaseUrl,window.CDL_CONFIG.supabaseAnonKey);const C=window.LEAD_CATALOG;let mode='individual',selected=new Set(),selectedAdds=new Set(),selectedCombo='Básico',activeProducts=[],quote=null,internalQuote=null,internalOpen=false,quoteTimer;
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',minimumFractionDigits:2,maximumFractionDigits:4});const num=v=>Number(v||0).toLocaleString('pt-BR');
async function login(){const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value,msg=document.getElementById('loginMsg');msg.textContent='';if(!email||!password){msg.textContent='Informe e-mail e senha.';return}const {error}=await sb.auth.signInWithPassword({email,password});if(error){msg.textContent='Acesso não autorizado. Confira e-mail e senha.';return}document.getElementById('password').value='';await boot()}
async function logout(){await sb.auth.signOut();location.reload()}
async function boot(){const {data:{session}}=await sb.auth.getSession();if(!session)return;document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');document.getElementById('userLabel').textContent=session.user.email||'';internalOpen=false;render()}
sb.auth.onAuthStateChange((_e,s)=>{if(!s) return;});
function setMode(m){mode=m;selected.clear();selectedAdds.clear();selectedCombo='Básico';activeProducts=[];quote=internalQuote=null;document.getElementById('individualArea').classList.toggle('hidden',m!=='individual');document.getElementById('comboArea').classList.toggle('hidden',m!=='combo');document.getElementById('tabInd').classList.toggle('active',m==='individual');document.getElementById('tabCombo').classList.toggle('active',m==='combo');render()}
function resetSelection(){selected.clear();selectedAdds.clear();selectedCombo='Básico';activeProducts=[];render()}
function productsForPerson(){const p=document.getElementById('person').value;return [...new Set(C.individual.filter(x=>x.person===p).map(x=>x.product))]}
function syncProducts(){const valid=productsForPerson();activeProducts=activeProducts.filter(x=>valid.includes(x));if(!activeProducts.length&&valid.length)activeProducts=[valid[0]]}
function addProduct(){const p=document.getElementById('productPicker').value;if(p&&!activeProducts.includes(p)){activeProducts.push(p);renderIndividual()}}
function removeProduct(p){p=decodeURIComponent(p);activeProducts=activeProducts.filter(x=>x!==p);[...selected].forEach(k=>{const o=JSON.parse(k);if(o.product===p)selected.delete(k)});renderIndividual()}
function selection(){if(mode==='individual')return [...selected].map(JSON.parse);return {level:selectedCombo,addons:[...selectedAdds]}}
function render(){if(mode==='individual')renderIndividual();else renderCombo();scheduleQuote()}
function renderIndividual(){const person=document.getElementById('person').value;syncProducts();const available=productsForPerson().filter(p=>!activeProducts.includes(p)),picker=document.getElementById('productPicker');picker.innerHTML=available.length?available.map(p=>`<option>${p}</option>`).join(''):'<option value="">Todos já adicionados</option>';picker.disabled=!available.length;document.getElementById('individualGroups').innerHTML=activeProducts.map(prod=>{const items=C.individual.filter(x=>x.person===person&&x.product===prod);return `<div class="product-block"><div class="product-head"><div><div class="eyebrow">Produto selecionado</div><b>${prod}</b></div><button class="ghost" onclick="removeProduct('${encodeURIComponent(prod)}')">Remover</button></div><div class="items">${items.map(x=>{const k=JSON.stringify({product:x.product,flag:x.flag});return `<label class="item"><input type="checkbox" ${selected.has(k)?'checked':''} onchange='toggleIndividual(${JSON.stringify(k)})'><span><b>${x.flag}</b><span>${selected.has(k)?itemCommercialLabel(x.product+' — '+x.flag):'Selecione para incluir na solução'}</span></span></label>`}).join('')}</div></div>`}).join('')}
function itemCommercialLabel(name){const i=quote?.items?.find(x=>x.name===name);return i?`Investimento: <strong>${money(i.commercial_unit)}</strong> / lead`:'Calculando investimento…'}
function toggleIndividual(k){selected.has(k)?selected.delete(k):selected.add(k);renderIndividual();scheduleQuote()}
function renderCombo(){const person=document.getElementById('person').value,cs=C.combos.filter(x=>x.person===person);if(!cs.some(x=>x.level===selectedCombo))selectedCombo=cs[0]?.level||'Básico';document.getElementById('comboCards').innerHTML=cs.map(c=>`<div class="combo ${c.level===selectedCombo?'active':''}" onclick="selectedCombo='${c.level}';renderCombo();scheduleQuote()"><h4>${c.level}</h4><div class="muted">${c.level===selectedCombo&&quote?`Investimento: <b>${money(quote.sale_unit)}</b> / lead`:'Selecione para simular'}</div><ul>${c.items.map(i=>`<li>${i}</li>`).join('')}</ul><button class="${c.level===selectedCombo?'primary':'ghost'}">${c.level===selectedCombo?'Selecionado':'Selecionar'}</button></div>`).join('');const adds=C.addons.filter(x=>x.person===person);document.getElementById('comboAdds').innerHTML=adds.map(x=>`<label class="item"><input type="checkbox" ${selectedAdds.has(x.name)?'checked':''} onchange='toggleAddon(${JSON.stringify(x.name)})'><span><b>${x.name}</b><span>${selectedAdds.has(x.name)?itemCommercialLabel('Adicional — '+x.name):'Opcional'}</span></span></label>`).join('')}
function toggleAddon(n){selectedAdds.has(n)?selectedAdds.delete(n):selectedAdds.add(n);renderCombo();scheduleQuote()}
function scheduleQuote(){clearTimeout(quoteTimer);quoteTimer=setTimeout(calculate,220)}
async function calculate(){const q=Math.max(0,+document.getElementById('qty').value||0),person=document.getElementById('person').value,sel=selection();document.getElementById('qtyLabel').textContent=num(q);if(!q){renderQuote(null);return}const empty=mode==='individual'?sel.length===0:!sel.level;if(empty){renderQuote(null);return}document.getElementById('quoteStatus').textContent='Calculando de forma segura…';const {data,error}=await sb.rpc('calculate_lead_quote',{p_mode:mode,p_person:person,p_qty:q,p_selection:sel});if(error){document.getElementById('quoteStatus').textContent='A calculadora segura ainda não está disponível. Verifique a migração do Supabase.';quote=null;return}quote=data;renderQuote(quote);if(internalOpen)await loadInternal();if(mode==='individual')renderIndividual();else renderCombo()}
function renderQuote(x){document.getElementById('salePrice').textContent=money(x?.sale_total||0);document.getElementById('saleUnit').textContent=money(x?.sale_unit||0);document.getElementById('bandLabel').textContent=x?.band||'—';document.getElementById('quoteStatus').textContent=x?'Preço comercial calculado com segurança.':'Selecione os itens para calcular.';document.getElementById('selectedList').innerHTML=x?.items?.length?x.items.map(i=>`<div class="selected-row"><span>${i.name}</span><b>${money(i.commercial_unit)} / lead</b></div>`).join(''):''}
async function toggleInternal(){if(internalOpen){internalOpen=false;internalQuote=null;document.getElementById('internalPanel').classList.add('hidden');document.getElementById('modeBadge').textContent='Modo Cliente';document.getElementById('modeBadge').classList.remove('internal');document.getElementById('internalBtn').textContent='Visão interna';return}const {data:{user}}=await sb.auth.getUser();const password=prompt('Digite novamente sua senha para abrir a visão interna.');if(password===null)return;const {error}=await sb.auth.signInWithPassword({email:user.email,password});if(error){alert('Senha incorreta.');return}internalOpen=true;document.getElementById('internalPanel').classList.remove('hidden');document.getElementById('modeBadge').textContent='Modo Interno';document.getElementById('modeBadge').classList.add('internal');document.getElementById('internalBtn').textContent='Voltar ao cliente';await loadInternal()}
async function loadInternal(){if(!quote)return;const q=Math.max(0,+document.getElementById('qty').value||0),person=document.getElementById('person').value;const {data,error}=await sb.rpc('calculate_lead_quote_internal',{p_mode:mode,p_person:person,p_qty:q,p_selection:selection()});if(error)return;internalQuote=data;document.getElementById('unitCost').textContent=money(data.unit_cost);document.getElementById('totalCost').textContent=money(data.cost_total);document.getElementById('markup').textContent=Math.round(Number(data.markup||0)*100)+'%'}
function clientData(){return {company:client.value.trim(),doc:doc.value.trim(),contact:contact.value.trim(),email:clientEmail.value.trim(),phone:phone.value.trim(),focus:focus.value.trim()}}
async function saveProposal(status='Rascunho'){if(!quote){alert('Monte uma simulação antes de salvar.');return null}const {data:{user}}=await sb.auth.getUser();const payload={created_by:user.id,status,mode,person:document.getElementById('person').value,quantity:+qty.value,client:clientData(),selection:selection(),quote};const {data,error}=await sb.from('lead_proposals').insert(payload).select('id,code').single();if(error){alert('Não foi possível salvar. Verifique se a migração do banco foi aplicada.');return null}alert(`Proposta ${data.code} salva.`);return data}
async function generateProposal(){const saved=await saveProposal('Gerada');if(!saved)return;const c=clientData(),w=window.open('','_blank'),rows=quote.items.map(i=>`<tr><td>${i.name}</td><td>${money(i.commercial_unit)} / lead</td></tr>`).join('');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${saved.code}</title><style>body{font-family:Arial;padding:42px;color:#142033;max-width:900px;margin:auto}h1{color:#071b33}.top{border-bottom:3px solid #0b62d6;padding-bottom:18px;margin-bottom:26px}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #ddd;text-align:left}.total{font-size:28px;font-weight:800;color:#0b62d6}.cta{margin-top:30px;padding:18px;background:#eef6ff}button{padding:10px 14px}</style></head><body><div class="top"><h1>Proposta Comercial • SPC Dados</h1><b>CDL Novo Hamburgo</b><p>${saved.code}</p></div><h3>${c.company||'Cliente'}</h3><p>${c.contact||''} ${c.email?`• ${c.email}`:''}</p><p><b>Solução:</b> ${mode==='individual'?'Dados individuais':'Combo de dados'} • ${quote.person}<br><b>Quantidade:</b> ${num(quote.quantity)} leads</p><table><thead><tr><th>Composição</th><th>Investimento por lead</th></tr></thead><tbody>${rows}</tbody></table><p class="total">Investimento total: ${money(quote.sale_total)}</p><div class="cta"><b>Próximo passo</b><p>Fale com seu consultor CDL para validar escopo, disponibilidade da base e condições da contratação.</p></div><button onclick="print()">Imprimir / salvar em PDF</button></body></html>`);w.document.close();showHistory(true)}
async function showHistory(open=true){document.getElementById('history').classList.toggle('hidden',!open);if(!open)return;const {data,error}=await sb.from('lead_proposals').select('code,created_at,status,mode,quantity,client,quote').order('created_at',{ascending:false}).limit(100);document.getElementById('historyList').innerHTML=error?'<p class="muted">Não foi possível carregar o histórico.</p>':data.length?`<table class="proposal-table"><thead><tr><th>Proposta</th><th>Cliente</th><th>Tipo</th><th>Valor</th><th>Data</th><th>Status</th></tr></thead><tbody>${data.map(p=>`<tr><td>${p.code}</td><td>${p.client?.company||'—'}</td><td>${p.mode==='individual'?'Individual':'Combo'}</td><td><b>${money(p.quote?.sale_total)}</b></td><td>${new Date(p.created_at).toLocaleDateString('pt-BR')}</td><td>${p.status}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">Nenhuma proposta salva.</p>'}
boot();