// Kanban comercial + histórico + controles administrativos
const CDL_FLOW=['Pendente','Proposta enviada','Proposta fechada','Aguardando envio da compra de leads do SPC Brasil','Compra de leads enviada para o cliente'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const flowStatus=s=>({'Nova':'Pendente','Em análise':'Pendente','Proposta gerada':'Proposta enviada','Respondida':'Proposta enviada','Encerrada':'Compra de leads enviada para o cliente','Rascunho':'Pendente','Gerada':'Proposta enviada','Enviada':'Proposta enviada','Aprovada':'Proposta fechada'}[s]||s||'Pendente');
let commercialView={request:'kanban',proposal:'kanban'},currentProfileRole=null,editingProposalId=null,editingProposalCode=null;

async function loadCurrentRole(){if(currentProfileRole!==null)return currentProfileRole;const {data:{user}}=await sb.auth.getUser();if(!user)return null;const {data}=await sb.from('profiles').select('role').eq('id',user.id).maybeSingle();currentProfileRole=data?.role||'';if(!currentProfileRole){const r=await sb.rpc('is_cdl_admin');if(!r.error&&r.data===true)currentProfileRole='admin'}return currentProfileRole}
const isAdmin=()=>currentProfileRole==='admin';
function statusSelect(type,x){return `<select onchange="changeCommercialStatus('${type}','${x.id}',this.value)">${CDL_FLOW.map(s=>`<option ${flowStatus(x.status)===s?'selected':''}>${s}</option>`).join('')}</select>`}
function card(x,type){const c=x.client||{},isP=type==='proposal';return `<article class="kanban-card"><div class="card-code">${esc(x.code)}</div><h4>${esc(c.company||'Cliente não informado')}</h4><div class="card-meta">${esc(c.contact||'')}${c.contact&&c.email?' • ':''}${esc(c.email||'')}</div><div class="card-meta">${isP?`${x.mode==='individual'?'Individual':'Combo'} • ${num(x.quantity)} leads • <b>${money(x.quote?.sale_total)}</b>`:`${esc(x.person)} • ${num(x.quantity)} leads`}</div><div class="card-meta">${new Date(x.created_at).toLocaleDateString('pt-BR')}</div><label class="card-label">Etapa</label>${statusSelect(type,x)}<div class="card-actions">${!isP?`<button class="secondary" onclick="loadRequestFromKanban('${x.id}')">Orçar</button>`:(isAdmin()?`<button class="ghost" onclick="editProposal('${x.id}')">Editar</button><button class="danger" onclick="deleteProposal('${x.id}','${esc(x.code)}')">Excluir</button>`:'')}</div></article>`}
function kanban(rows,type){return `<div class="kanban">${CDL_FLOW.map(st=>{const list=rows.filter(x=>flowStatus(x.status)===st);return `<div class="kanban-col"><div class="kanban-head"><b>${st}</b><span>${list.length}</span></div><div class="kanban-stack">${list.length?list.map(x=>card(x,type)).join(''):'<div class="kanban-empty">Nenhum registro</div>'}</div></div>`}).join('')}</div>`}
function historyTable(rows,type){const isP=type==='proposal';return rows.length?`<div style="overflow:auto"><table class="proposal-table"><thead><tr><th>Código</th><th>Cliente</th><th>${isP?'Tipo':'Necessidade'}</th><th>Quantidade</th>${isP?'<th>Valor</th>':''}<th>Data</th><th>Etapa</th><th>Ações</th></tr></thead><tbody>${rows.map(x=>{const c=x.client||{};return `<tr><td><b>${esc(x.code)}</b></td><td>${esc(c.company||'—')}<br><span class="muted">${esc(c.contact||'')}</span></td><td>${isP?(x.mode==='individual'?'Individual':'Combo'):esc(x.person)}</td><td>${num(x.quantity)}</td>${isP?`<td><b>${money(x.quote?.sale_total)}</b></td>`:''}<td>${new Date(x.created_at).toLocaleDateString('pt-BR')}</td><td>${statusSelect(type,x)}</td><td><div class="card-actions" style="margin:0">${!isP?`<button class="secondary" onclick="loadRequestFromKanban('${x.id}')">Orçar</button>`:(isAdmin()?`<button class="ghost" onclick="editProposal('${x.id}')">Editar</button><button class="danger" onclick="deleteProposal('${x.id}','${esc(x.code)}')">Excluir</button>`:'')}</div></td></tr>`}).join('')}</tbody></table></div>`:'<p class="muted">Nenhum registro encontrado.</p>'}
function toolbar(type){const v=commercialView[type];return `<div style="display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:18px;flex-wrap:wrap"><div class="muted" style="font-size:13px">${type==='proposal'?(isAdmin()?'Perfil administrador: edição e exclusão habilitadas.':'Visualização de propostas.'):'Acompanhe o andamento comercial das solicitações.'}</div><div class="tabs" style="margin:0"><button class="tab ${v==='kanban'?'active':''}" onclick="setCommercialView('${type}','kanban')">Kanban</button><button class="tab ${v==='history'?'active':''}" onclick="setCommercialView('${type}','history')">Histórico</button></div></div>`}
window.setCommercialView=function(type,view){commercialView[type]=view;type==='proposal'?showHistory(true):showRequests(true)};

window.showRequests=async function(open=true){if(!open)return;await loadCurrentRole();const box=document.getElementById('requestList');box.innerHTML='<p class="muted">Carregando solicitações…</p>';const {data,error}=await sb.from('lead_quote_requests').select('id,code,created_at,status,mode,person,quantity,client,selection,notes').order('created_at',{ascending:false}).limit(200);if(error){console.error(error);box.innerHTML='<p class="muted">Não foi possível carregar as solicitações.</p>';return}const rows=data||[];box.innerHTML=toolbar('request')+(commercialView.request==='kanban'?kanban(rows,'request'):historyTable(rows,'request'))};
window.showHistory=async function(open=true){if(!open)return;await loadCurrentRole();const box=document.getElementById('historyList');box.innerHTML='<p class="muted">Carregando propostas…</p>';const {data,error}=await sb.from('lead_proposals').select('id,code,created_at,status,mode,person,quantity,client,selection,quote').order('created_at',{ascending:false}).limit(200);if(error){console.error(error);box.innerHTML='<p class="muted">Não foi possível carregar o histórico de propostas.</p>';return}const rows=data||[];box.innerHTML=toolbar('proposal')+(commercialView.proposal==='kanban'?kanban(rows,'proposal'):historyTable(rows,'proposal'))};
window.changeCommercialStatus=async function(type,id,status){const table=type==='proposal'?'lead_proposals':'lead_quote_requests';const {error}=await sb.from(table).update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error){console.error(error);alert('Não foi possível alterar a etapa.');return}type==='proposal'?showHistory(true):showRequests(true)};
window.loadRequestFromKanban=async function(id){await loadRequest(id);openSection('calculator')};

function fillProposalInCalculator(p){mode=p.mode;document.getElementById('person').value=p.person;document.getElementById('qty').value=p.quantity;const c=p.client||{};document.getElementById('client').value=c.company||'';document.getElementById('doc').value=c.doc||'';document.getElementById('contact').value=c.contact||'';document.getElementById('clientEmail').value=c.email||'';document.getElementById('phone').value=c.phone||'';document.getElementById('focus').value=c.focus||'';selected.clear();selectedAdds.clear();activeProducts=[];if(mode==='individual'){(p.selection||[]).forEach(x=>{selected.add(JSON.stringify({product:x.product,flag:x.flag}));if(!activeProducts.includes(x.product))activeProducts.push(x.product)})}else{selectedCombo=p.selection?.level||'Básico';(p.selection?.addons||[]).forEach(x=>selectedAdds.add(x))}document.getElementById('individualArea').classList.toggle('hidden',mode!=='individual');document.getElementById('comboArea').classList.toggle('hidden',mode!=='combo');document.getElementById('tabInd').classList.toggle('active',mode==='individual');document.getElementById('tabCombo').classList.toggle('active',mode==='combo');openSection('calculator');render()}
window.editProposal=async function(id){await loadCurrentRole();if(!isAdmin()){alert('A edição de propostas é exclusiva do administrador.');return}const {data:p,error}=await sb.from('lead_proposals').select('*').eq('id',id).single();if(error||!p){alert('Não foi possível abrir a proposta.');return}editingProposalId=p.id;editingProposalCode=p.code;fillProposalInCalculator(p);alert(`Editando ${p.code}. Ao salvar ou gerar a proposta, este mesmo registro será atualizado.`)};
window.deleteProposal=async function(id,code){await loadCurrentRole();if(!isAdmin()){alert('A exclusão de propostas é exclusiva do administrador.');return}if(!confirm(`Excluir definitivamente a proposta ${code}? Esta ação não pode ser desfeita.`))return;const {error}=await sb.from('lead_proposals').delete().eq('id',id);if(error){console.error(error);alert('Não foi possível excluir a proposta.');return}await showHistory(true)};

window.saveProposal=async function(status='Rascunho',silent=false){if(!quote){alert('Monte uma simulação antes de salvar.');return null}const normalized=status==='Gerada'?'Proposta enviada':status;const {data:{user}}=await sb.auth.getUser();const payload={status:normalized,mode,person:document.getElementById('person').value,quantity:+document.getElementById('qty').value,client:clientData(),selection:selection(),quote,updated_at:new Date().toISOString()};if(editingProposalId){await loadCurrentRole();if(!isAdmin()){if(!silent)alert('A edição desta proposta é exclusiva do administrador.');return null}const {data,error}=await sb.from('lead_proposals').update(payload).eq('id',editingProposalId).select('id,code').single();if(error){console.error(error);if(!silent)alert('Não foi possível atualizar a proposta.');return null}const code=data.code;editingProposalId=null;editingProposalCode=null;if(!silent)alert(`Proposta ${code} atualizada.`);return data}const insertPayload={...payload,created_by:user.id};const {data,error}=await sb.from('lead_proposals').insert(insertPayload).select('id,code').single();if(error){console.error(error);if(!silent)alert('Não foi possível salvar a simulação.');return null}if(!silent)alert(`Proposta ${data.code} salva.`);return data};
