// Kanban comercial: histórico + workflow no mesmo Portal Comercial.
const CDL_FLOW=['Pendente','Proposta enviada','Proposta fechada','Aguardando envio da compra de leads do SPC Brasil','Compra de leads enviada para o cliente'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const flowStatus=s=>({'Nova':'Pendente','Em análise':'Pendente','Proposta gerada':'Proposta enviada','Respondida':'Proposta enviada','Encerrada':'Compra de leads enviada para o cliente','Rascunho':'Pendente','Gerada':'Pendente','Enviada':'Proposta enviada','Aprovada':'Proposta fechada'}[s]||s||'Pendente');
function kanban(title,rows,type){return `<div class="kanban">${CDL_FLOW.map(st=>{const list=rows.filter(x=>flowStatus(x.status)===st);return `<div class="kanban-col"><div class="kanban-head"><b>${st}</b><span>${list.length}</span></div><div class="kanban-stack">${list.length?list.map(x=>card(x,type)).join(''):'<div class="kanban-empty">Nenhum registro</div>'}</div></div>`}).join('')}</div>`}
function card(x,type){const c=x.client||{};const isP=type==='proposal';return `<article class="kanban-card"><div class="card-code">${esc(x.code)}</div><h4>${esc(c.company||'Cliente não informado')}</h4><div class="card-meta">${esc(c.contact||'')}${c.contact&&c.email?' • ':''}${esc(c.email||'')}</div><div class="card-meta">${isP?`${x.mode==='individual'?'Individual':'Combo'} • ${num(x.quantity)} leads • <b>${money(x.quote?.sale_total)}</b>`:`${esc(x.person)} • ${num(x.quantity)} leads`}</div><div class="card-meta">${new Date(x.created_at).toLocaleDateString('pt-BR')}</div><label class="card-label">Etapa</label><select onchange="changeCommercialStatus('${type}','${x.id}',this.value)">${CDL_FLOW.map(s=>`<option ${flowStatus(x.status)===s?'selected':''}>${s}</option>`).join('')}</select><div class="card-actions">${!isP?`<button class="secondary" onclick="loadRequestFromKanban('${x.id}')">Orçar</button>`:`<button class="ghost" onclick="editProposal('${x.id}')">Editar</button><button class="danger" onclick="deleteProposal('${x.id}','${esc(x.code)}')">Excluir</button>`}</div></article>`}
window.showRequests=async function(open=true){if(!open)return;const box=document.getElementById('requestList');box.innerHTML='<p class="muted">Carregando solicitações…</p>';const {data,error}=await sb.from('lead_quote_requests').select('id,code,created_at,status,mode,person,quantity,client,selection,notes').order('created_at',{ascending:false}).limit(200);if(error){console.error(error);box.innerHTML='<p class="muted">Não foi possível carregar as solicitações.</p>';return}box.innerHTML=kanban('Solicitações',data||[],'request')};
window.showHistory=async function(open=true){if(!open)return;const box=document.getElementById('historyList');box.innerHTML='<p class="muted">Carregando propostas…</p>';const {data,error}=await sb.from('lead_proposals').select('id,code,created_at,status,mode,person,quantity,client,selection,quote').order('created_at',{ascending:false}).limit(200);if(error){console.error(error);box.innerHTML='<p class="muted">Não foi possível carregar o histórico de propostas.</p>';return}box.innerHTML=kanban('Propostas',data||[],'proposal')};
window.changeCommercialStatus=async function(type,id,status){const table=type==='proposal'?'lead_proposals':'lead_quote_requests';const {error}=await sb.from(table).update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error){console.error(error);alert('Não foi possível alterar a etapa. Execute a migração 006 no Supabase e tente novamente.');return}type==='proposal'?showHistory(true):showRequests(true)};
window.loadRequestFromKanban=async function(id){await loadRequest(id);openSection('calculator')};
window.editProposal=async function(id){const {data:p,error}=await sb.from('lead_proposals').select('*').eq('id',id).single();if(error||!p){alert('Não foi possível abrir a proposta.');return}mode=p.mode;document.getElementById('person').value=p.person;document.getElementById('qty').value=p.quantity;const c=p.client||{};document.getElementById('client').value=c.company||'';document.getElementById('doc').value=c.doc||'';document.getElementById('contact').value=c.contact||'';document.getElementById('clientEmail').value=c.email||'';document.getElementById('phone').value=c.phone||'';document.getElementById('focus').value=c.focus||'';selected.clear();selectedAdds.clear();activeProducts=[];if(mode==='individual'){(p.selection||[]).forEach(x=>{selected.add(JSON.stringify({product:x.product,flag:x.flag}));if(!activeProducts.includes(x.product))activeProducts.push(x.product)})}else{selectedCombo=p.selection?.level||'Básico';(p.selection?.addons||[]).forEach(x=>selectedAdds.add(x))}document.getElementById('individualArea').classList.toggle('hidden',mode!=='individual');document.getElementById('comboArea').classList.toggle('hidden',mode!=='combo');document.getElementById('tabInd').classList.toggle('active',mode==='individual');document.getElementById('tabCombo').classList.toggle('active',mode==='combo');openSection('calculator');render();alert(`Proposta ${p.code} carregada para edição. Ao salvar, será criada uma nova versão; a original permanece no histórico.`)};
window.deleteProposal=async function(id,code){if(!confirm(`Excluir definitivamente a proposta ${code}? Esta ação é exclusiva de administrador e não pode ser desfeita.`))return;const {error}=await sb.from('lead_proposals').delete().eq('id',id);if(error){console.error(error);alert('Exclusão não autorizada. Confirme que seu usuário está como administrador e que a migração 006 foi executada.');return}await showHistory(true)};
