const sb=window.supabase.createClient(window.CDL_CONFIG.supabaseUrl,window.CDL_CONFIG.supabaseAnonKey);
const $=id=>document.getElementById(id);let view='requests',rows=[];
const num=v=>Number(v||0).toLocaleString('pt-BR');const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
async function login(){const email=$('email').value.trim(),password=$('password').value;$('loginMsg').textContent='';if(!email||!password){$('loginMsg').textContent='Informe e-mail e senha.';return}const {error}=await sb.auth.signInWithPassword({email,password});if(error){$('loginMsg').textContent='Acesso não autorizado.';return}await boot()}
async function logout(){await sb.auth.signOut();location.reload()}
async function boot(){const {data:{session}}=await sb.auth.getSession();if(!session)return;$('login').classList.add('hidden');$('app').classList.remove('hidden');$('userLabel').textContent=session.user.email||'';await load()}
function setView(v){view=v;$('tabRequests').classList.toggle('active',v==='requests');$('tabProposals').classList.toggle('active',v==='proposals');$('search').value='';$('statusFilter').innerHTML='<option value="">Todos</option>';load()}
async function load(){if(view==='requests'){const {data,error}=await sb.from('lead_quote_requests').select('id,code,created_at,status,mode,person,quantity,client,selection,notes').order('created_at',{ascending:false}).limit(300);if(error){$('content').innerHTML='<div class="empty">Não foi possível carregar as solicitações.</div>';return}rows=data||[];['Nova','Em análise','Proposta gerada','Respondida','Encerrada'].forEach(s=>$('statusFilter').insertAdjacentHTML('beforeend',`<option>${s}</option>`));}else{const {data,error}=await sb.from('lead_proposals').select('id,code,created_at,status,mode,person,quantity,client,selection,quote').order('created_at',{ascending:false}).limit(300);if(error){$('content').innerHTML='<div class="empty">Não foi possível carregar as propostas.</div>';return}rows=data||[];['Rascunho','Gerada','Enviada','Aprovada','Perdida','Cancelada'].forEach(s=>$('statusFilter').insertAdjacentHTML('beforeend',`<option>${s}</option>`));}render()}
function render(){const q=$('search').value.trim().toLowerCase(),st=$('statusFilter').value;const data=rows.filter(r=>{const c=r.client||{};const hay=[r.code,c.company,c.contact,c.email].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!st||r.status===st)});if(!data.length){$('content').innerHTML='<div class="empty">Nenhum registro encontrado.</div>';return}if(view==='requests'){$('content').innerHTML=`<table><thead><tr><th>Solicitação</th><th>Empresa / contato</th><th>Necessidade</th><th>Quantidade</th><th>Data</th><th>Status</th><th></th></tr></thead><tbody>${data.map(r=>`<tr><td><b>${r.code}</b></td><td>${r.client?.company||'—'}<br><span class="muted">${r.client?.contact||''}</span></td><td>${r.client?.need||((r.mode==='individual'?'Individual':'Combo')+' • '+r.person)}${r.client?.existingData?`<br><span class="muted">Já possui: ${r.client.existingData}</span>`:''}</td><td>${num(r.quantity)}</td><td>${new Date(r.created_at).toLocaleDateString('pt-BR')}</td><td><span class="status">${r.status}</span></td><td><a class="secondary linkbtn" href="index.html?request=${encodeURIComponent(r.id)}">Carregar na calculadora</a></td></tr>`).join('')}</tbody></table>`}else{$('content').innerHTML=`<table><thead><tr><th>Proposta</th><th>Cliente</th><th>Tipo</th><th>Quantidade</th><th>Valor</th><th>Data</th><th>Status</th></tr></thead><tbody>${data.map(r=>`<tr><td><b>${r.code}</b></td><td>${r.client?.company||'—'}<br><span class="muted">${r.client?.contact||''}</span></td><td>${r.mode==='individual'?'Individual':'Combo'} • ${r.person}</td><td>${num(r.quantity)}</td><td><b>${money(r.quote?.sale_total)}</b></td><td>${new Date(r.created_at).toLocaleDateString('pt-BR')}</td><td><span class="status">${r.status}</span></td></tr>`).join('')}</tbody></table>`}}
$('loginBtn').addEventListener('click',login);$('logoutBtn').addEventListener('click',logout);$('tabRequests').addEventListener('click',()=>setView('requests'));$('tabProposals').addEventListener('click',()=>setView('proposals'));$('refreshBtn').addEventListener('click',load);$('search').addEventListener('input',render);$('statusFilter').addEventListener('change',render);boot();