// Recomendação inteligente de combos + desconto comercial opcional
let commercialDiscountPercent=0;
let grossQuote=null;
let currentSmartRecommendation=null;
let smartOriginalRequest=null;
let smartComparison=null;
let smartDrafts={individual:null,combo:null};

const normLeadName=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+1$/,'').replace(/^nome$/,'nome completo').replace(/^endereco$/,'endereco completo').replace(/^data de abertura$/,'data de fundacao').replace(/^restricao spc$/,'restricao 1 bureau').replace(/^restricao spc e serasa$/,'restricao 2 bureaux').replace(/^quadro social administrativo$/,'quadro social e administrativo');

function ensureSmartStyles(){if(document.getElementById('smartQuoteStyles'))return;const s=document.createElement('style');s.id='smartQuoteStyles';s.textContent=`
.smart-switch{display:none;background:#071b33;color:#fff;border-radius:16px;padding:14px 18px;margin:0 0 16px;box-shadow:0 8px 24px rgba(7,27,51,.14)}.smart-switch.show{display:flex;align-items:center;justify-content:space-between;gap:14px;flex-wrap:wrap}.smart-switch-title{font-weight:900;font-size:15px}.smart-switch-sub{font-size:12px;color:#cbd8e8;margin-top:3px}.smart-switch-actions{display:flex;gap:7px;flex-wrap:wrap}.smart-switch button{border:1px solid rgba(255,255,255,.3);background:transparent;color:#fff;border-radius:10px;padding:9px 13px;font-weight:900}.smart-switch button.active{background:#fff;color:#084fae;border-color:#fff}.smart-rec{border:1px solid #b9d5fb;background:#f6faff;border-radius:16px;padding:18px;margin:0 0 18px;box-shadow:0 5px 18px rgba(11,98,214,.06)}.smart-rec-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;flex-wrap:wrap}.smart-rec h3{margin:4px 0;color:#071b33}.smart-chip{display:inline-flex;align-items:center;border-radius:999px;background:#e8f1ff;color:#084fae;font-size:11px;font-weight:900;padding:6px 9px;margin:4px 5px 0 0}.smart-chip.ok{background:#e7f6ef;color:#176b4d}.smart-chip.warn{background:#fff4df;color:#8a5a00}.smart-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:14px}.smart-box{background:#fff;border:1px solid #dce3ed;border-radius:12px;padding:12px;font-size:12px;line-height:1.45}.smart-box b{display:block;color:#071b33;margin-bottom:5px}.smart-list{margin:5px 0 0;padding-left:18px}.smart-note{font-size:12px;color:#667085;margin-top:12px;line-height:1.45}.smart-compare{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.smart-price{font-size:22px;font-weight:900;color:#071b33;margin:4px 0}.smart-price.best{color:#176b4d}.smart-selected{border:2px solid #0b62d6}.smart-diff{margin-top:8px;font-size:12px;font-weight:800}.smart-missing{margin-top:12px;background:#fff8e8;border:1px solid #efd39a;border-radius:12px;padding:13px}.smart-missing b{color:#7a4b00}.smart-original{margin-top:12px;background:#fff;border:1px solid #dce3ed;border-radius:12px;padding:12px}@media(max-width:760px){.smart-grid,.smart-compare{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function escSmart(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function smartList(arr,empty='Nenhum'){return arr?.length?`<ul class="smart-list">${arr.map(x=>`<li>${escSmart(x)}</li>`).join('')}</ul>`:`<span class="muted">${empty}</span>`}
function ensureSmartSwitch(){ensureSmartStyles();let bar=document.getElementById('smartModeSwitch');if(bar)return bar;const top=document.querySelector('#calculatorView .toprow');if(!top)return null;bar=document.createElement('div');bar.id='smartModeSwitch';bar.className='smart-switch';top.insertAdjacentElement('afterend',bar);return bar}
function ensureRecommendationUI(){ensureSmartStyles();let box=document.getElementById('smartRecommendation');if(box)return box;const panel=document.querySelector('#calculatorView .grid2 > .panel');if(!panel)return null;box=document.createElement('div');box.id='smartRecommendation';box.className='smart-rec hidden';panel.insertBefore(box,panel.firstChild);return box}
function clearRecommendation(resetMemory=false){currentSmartRecommendation=null;const box=document.getElementById('smartRecommendation');if(box){box.classList.add('hidden');box.innerHTML=''}const bar=document.getElementById('smartModeSwitch');if(bar){bar.classList.remove('show');bar.innerHTML=''}if(resetMemory){smartOriginalRequest=null;smartComparison=null;smartDrafts={individual:null,combo:null}}}

function snapshotSmartDraft(){if(!smartOriginalRequest)return;if(mode==='individual')smartDrafts.individual={selected:[...selected],activeProducts:[...activeProducts]};else smartDrafts.combo={selectedCombo,selectedAdds:[...selectedAdds]}}
function originalIndividualDraft(r){const keys=[],products=[];(r.selection||[]).forEach(x=>{if(!x?.product||!x?.flag)return;keys.push(JSON.stringify({product:x.product,flag:x.flag}));if(!products.includes(x.product))products.push(x.product)});return {selected:keys,activeProducts:products}}
function suggestedComboDraft(rec){return {selectedCombo:rec.combo.level,selectedAdds:[...rec.addons]}}
function applyIndividualDraft(d){mode='individual';selected.clear();selectedAdds.clear();activeProducts=[];(d?.selected||[]).forEach(k=>selected.add(k));activeProducts=[...(d?.activeProducts||[])];document.getElementById('individualArea').classList.remove('hidden');document.getElementById('comboArea').classList.add('hidden');document.getElementById('tabInd').classList.add('active');document.getElementById('tabCombo').classList.remove('active')}
function applyComboDraft(d){mode='combo';selected.clear();selectedAdds.clear();activeProducts=[];selectedCombo=d?.selectedCombo||smartComparison?.recommendation?.combo?.level||'Básico';(d?.selectedAdds||[]).forEach(x=>selectedAdds.add(x));document.getElementById('individualArea').classList.add('hidden');document.getElementById('comboArea').classList.remove('hidden');document.getElementById('tabInd').classList.remove('active');document.getElementById('tabCombo').classList.add('active')}

function renderSmartSwitch(activeMode){const bar=ensureSmartSwitch();if(!bar)return;if(!smartOriginalRequest||!smartComparison?.recommendation){bar.classList.remove('show');bar.innerHTML='';return}const rec=smartComparison.recommendation;bar.innerHTML=`<div><div class="smart-switch-title">Cotação ${escSmart(smartOriginalRequest.code||'')} • pedido original preservado</div><div class="smart-switch-sub">Abra o Individual como base fiel do pedido e use o Combo ${escSmart(rec.combo.level)} como alternativa comercial.</div></div><div class="smart-switch-actions"><button class="${activeMode==='individual'?'active':''}" onclick="showSmartIndividual()">Individual</button><button class="${activeMode==='combo'?'active':''}" onclick="showSmartCombo()">Combo recomendado</button></div>`;bar.classList.add('show')}
function comparisonHtml(activeMode){if(!smartComparison?.comboQuote||!smartComparison?.individualQuote)return '';const cv=Number(smartComparison.comboQuote.sale_total||0),iv=Number(smartComparison.individualQuote.sale_total||0),best=Math.min(cv,iv),diff=Math.abs(cv-iv);return `<div class="smart-compare"><div class="smart-box ${activeMode==='individual'?'smart-selected':''}"><b>Individual</b><div class="smart-price ${iv===best?'best':''}">${money(iv)}</div><span class="muted">Pedido original do cliente</span>${iv===best?'<div class="smart-diff">✓ Menor investimento</div>':''}</div><div class="smart-box ${activeMode==='combo'?'smart-selected':''}"><b>Combo ${escSmart(smartComparison.recommendation.combo.level)}</b><div class="smart-price ${cv===best?'best':''}">${money(cv)}</div><span class="muted">Combo sugerido + adicionais precificados</span>${cv===best?'<div class="smart-diff">✓ Menor investimento</div>':''}</div></div><div class="smart-note">Diferença: <b>${money(diff)}</b>. Os dois rascunhos são preservados quando você alterna.</div>`}
function comboMissingHtml(rec){const requestedMissing=[...new Set([...(rec.addons||[]),...(rec.unsupportedNames||[])])];if(!requestedMissing.length)return `<div class="smart-missing"><b>✓ O combo sugerido cobre o pedido sem pendências.</b></div>`;return `<div class="smart-missing"><b>⚠ O que falta complementar no Combo ${escSmart(rec.combo.level)}</b>${smartList(requestedMissing)}<div class="smart-note">Os itens disponíveis como adicional já entram selecionados na montagem sugerida. Os demais precisam ser avaliados/incluídos manualmente. Esta lista representa o que o cliente pediu e não está dentro do pacote-base.</div></div>`}
function renderSmartRecommendation(rec,requestCode,activeMode='individual'){const box=ensureRecommendationUI();if(!box||!rec)return;currentSmartRecommendation=rec;renderSmartSwitch(activeMode);const total=rec.requestedNames.length||1,inside=rec.coveredNames.length;box.innerHTML=`<div class="smart-rec-head"><div><div class="eyebrow">Sugestão inteligente • ${escSmart(requestCode||'cotação')}</div><h3>Pedido original + alternativa de Combo ${escSmart(rec.combo.level)}</h3><div class="muted" style="font-size:13px">O Individual permanece como tradução fiel da solicitação. O combo é uma alternativa que você pode montar e ajustar sem perder a primeira composição.</div></div><div><span class="smart-chip">${inside} de ${total} flags já estão no combo-base</span><span class="smart-chip ${rec.addons.length<=2?'ok':'warn'}">${rec.addons.length} adicional(is)</span></div></div><div class="smart-original"><b>Solicitação original do cliente</b>${smartList(rec.requestedNames)}</div><div class="smart-grid"><div class="smart-box"><b>Já contemplado no combo</b>${smartList(rec.coveredNames)}</div><div class="smart-box"><b>Adicionais sugeridos</b>${smartList(rec.addons,'Nenhum adicional necessário.')}</div><div class="smart-box"><b>Benefícios extras do combo</b>${smartList(rec.extraComboNames,'Nenhum extra não solicitado.')}</div></div>${comboMissingHtml(rec)}${comparisonHtml(activeMode)}`;box.classList.remove('hidden')}

function ensureDiscountUI(){const actions=document.querySelector('#calculatorView .summary .actions');if(!actions||document.getElementById('discountBox'))return;const box=document.createElement('div');box.id='discountBox';box.className='internal-box';box.style.cssText='margin-top:14px;background:#f8fbff;border-color:#cfe0f6';box.innerHTML=`<div class="eyebrow">Condição comercial</div><label style="margin:8px 0 6px">Desconto na proposta (%)</label><input id="proposalDiscount" type="number" min="0" max="100" step="0.1" value="0" style="width:100%"><div id="discountInfo" class="muted" style="font-size:12px;margin-top:7px">Opcional. Deixe 0 para manter o valor calculado.</div>`;actions.parentNode.insertBefore(box,actions);document.getElementById('proposalDiscount').addEventListener('input',e=>{commercialDiscountPercent=Math.min(100,Math.max(0,Number(e.target.value)||0));applyCommercialDiscount()})}
const baseRenderQuote=window.renderQuote;window.renderQuote=function(x){ensureDiscountUI();if(x&&!x._discount_applied){grossQuote=JSON.parse(JSON.stringify(x));applyCommercialDiscount(false);return}return baseRenderQuote(x)};
function applyCommercialDiscount(render=true){if(!grossQuote){if(render)baseRenderQuote(quote);return}const pct=commercialDiscountPercent/100,q=JSON.parse(JSON.stringify(grossQuote));q.gross_sale_total=Number(grossQuote.sale_total||0);q.gross_sale_unit=Number(grossQuote.sale_unit||0);q.discount_percent=commercialDiscountPercent;q.discount_amount=Number((q.gross_sale_total*pct).toFixed(2));q.sale_total=Number((q.gross_sale_total*(1-pct)).toFixed(2));q.sale_unit=Number((q.gross_sale_unit*(1-pct)).toFixed(4));q.items=(grossQuote.items||[]).map(i=>({...i,commercial_unit:Number((Number(i.commercial_unit||0)*(1-pct)).toFixed(4))}));q._discount_applied=true;quote=q;baseRenderQuote(q);const info=document.getElementById('discountInfo');if(info)info.innerHTML=commercialDiscountPercent>0?`Valor original: <b>${money(q.gross_sale_total)}</b> • Desconto: <b>${commercialDiscountPercent.toLocaleString('pt-BR')}%</b> (${money(q.discount_amount)})`:'Opcional. Deixe 0 para manter o valor calculado.'}
function resetCommercialDiscount(){commercialDiscountPercent=0;grossQuote=null;const el=document.getElementById('proposalDiscount');if(el)el.value='0';const info=document.getElementById('discountInfo');if(info)info.textContent='Opcional. Deixe 0 para manter o valor calculado.'}
function requestFlagMap(r){const map=new Map();(Array.isArray(r.selection)?r.selection:[]).forEach(x=>{const n=normLeadName(x?.flag);if(n&&!map.has(n))map.set(n,x.flag)});return map}
async function recommendComboForRequest(r){if(r.mode!=='individual'||!Array.isArray(r.selection)||!r.selection.length)return null;const person=r.person,requestedMap=requestFlagMap(r),requested=[...requestedMap.keys()],combos=(C.combos||[]).filter(x=>x.person===person),addons=(C.addons||[]).filter(x=>x.person===person),addonByNorm=new Map(addons.map(a=>[normLeadName(a.name),a.name]));const {data:individualQuote,error:individualError}=await sb.rpc('calculate_lead_quote',{p_mode:'individual',p_person:person,p_qty:r.quantity,p_selection:r.selection});const candidates=[];for(const combo of combos){const itemMap=new Map((combo.items||[]).map(x=>[normLeadName(x),x])),covered=requested.filter(f=>itemMap.has(f)),missing=requested.filter(f=>!itemMap.has(f)),supportedMissing=missing.filter(f=>addonByNorm.has(f)),unsupported=missing.filter(f=>!addonByNorm.has(f)),neededAdds=[...new Set(supportedMissing.map(f=>addonByNorm.get(f)))],extraCombo=[...itemMap.keys()].filter(f=>!requestedMap.has(f)).map(f=>itemMap.get(f));if(neededAdds.length>2)continue;const {data,error}=await sb.rpc('calculate_lead_quote',{p_mode:'combo',p_person:person,p_qty:r.quantity,p_selection:{level:combo.level,addons:neededAdds}});if(error||!data)continue;candidates.push({combo,addons:neededAdds,quote:data,coveredNames:covered.map(x=>requestedMap.get(x)),requestedNames:requested.map(x=>requestedMap.get(x)),unsupportedNames:unsupported.map(x=>requestedMap.get(x)),extraComboNames:extraCombo,directCoverage:covered.length})}if(!candidates.length)return {recommendation:null,individualQuote:individualError?null:individualQuote};candidates.sort((a,b)=>a.unsupportedNames.length-b.unsupportedNames.length||a.addons.length-b.addons.length||a.extraComboNames.length-b.extraComboNames.length||b.directCoverage-a.directCoverage||Number(a.quote.sale_total)-Number(b.quote.sale_total));return {recommendation:candidates[0],individualQuote:individualError?null:individualQuote}}
function fillBaseRequest(r){currentRequestId=r.id;document.getElementById('person').value=r.person;document.getElementById('qty').value=r.quantity;const c=r.client||{};document.getElementById('client').value=c.company||'';document.getElementById('doc').value=c.doc||'';document.getElementById('contact').value=c.contact||'';document.getElementById('clientEmail').value=c.email||'';document.getElementById('phone').value=c.phone||'';document.getElementById('focus').value=c.focus||''}

window.showSmartIndividual=function(){if(!smartOriginalRequest||!smartComparison?.recommendation)return;snapshotSmartDraft();resetCommercialDiscount();fillBaseRequest(smartOriginalRequest);applyIndividualDraft(smartDrafts.individual||originalIndividualDraft(smartOriginalRequest));render();renderSmartRecommendation(smartComparison.recommendation,smartOriginalRequest.code,'individual');window.scrollTo({top:0,behavior:'smooth'})};
window.showSmartCombo=function(){if(!smartOriginalRequest||!smartComparison?.recommendation)return;snapshotSmartDraft();resetCommercialDiscount();fillBaseRequest(smartOriginalRequest);applyComboDraft(smartDrafts.combo||suggestedComboDraft(smartComparison.recommendation));render();renderSmartRecommendation(smartComparison.recommendation,smartOriginalRequest.code,'combo');window.scrollTo({top:0,behavior:'smooth'})};
window.openOriginalRequestIndividual=window.showSmartIndividual;

const originalSetMode=window.setMode;
window.setMode=function(m){if(!smartOriginalRequest||!smartComparison?.recommendation)return originalSetMode(m);if(m==='individual')return window.showSmartIndividual();if(m==='combo')return window.showSmartCombo();return originalSetMode(m)};

const originalLoadRequestFromKanban=window.loadRequestFromKanban;
window.loadRequestFromKanban=async function(id){const {data:r,error}=await sb.from('lead_quote_requests').select('*').eq('id',id).single();if(error||!r){alert('Não foi possível carregar esta solicitação na calculadora.');return}resetCommercialDiscount();clearRecommendation(true);smartOriginalRequest=r;const result=await recommendComboForRequest(r),rec=result?.recommendation;if(!rec){await originalLoadRequestFromKanban(id);smartOriginalRequest=r;return}smartComparison={recommendation:rec,comboQuote:rec.quote,individualQuote:result.individualQuote};smartDrafts={individual:originalIndividualDraft(r),combo:suggestedComboDraft(rec)};fillBaseRequest(r);applyIndividualDraft(smartDrafts.individual);const {data:{user}}=await sb.auth.getUser();await sb.from('lead_quote_requests').update({handled_by:user?.id||null,updated_at:new Date().toISOString()}).eq('id',id);openSection('calculator');render();renderSmartRecommendation(rec,r.code,'individual');window.scrollTo({top:0,behavior:'smooth'})};

ensureDiscountUI();ensureRecommendationUI();ensureSmartSwitch();