const sb=window.supabase.createClient(window.CDL_CONFIG.supabaseUrl,window.CDL_CONFIG.supabaseAnonKey);const C=window.LEAD_CATALOG;let mode='individual',selected=new Set(),selectedAdds=new Set(),selectedCombo='Básico',activeProducts=[];
function productsForPerson(){const p=person.value;return [...new Set(C.individual.filter(x=>x.person===p).map(x=>x.product))]}
function syncProducts(){const valid=productsForPerson();activeProducts=activeProducts.filter(x=>valid.includes(x));if(!activeProducts.length&&valid.length)activeProducts=[valid[0]]}
function selection(){if(mode==='individual')return [...selected].map(JSON.parse);return {level:selectedCombo,addons:[...selectedAdds]}}
function setMode(m){mode=m;selected.clear();selectedAdds.clear();selectedCombo='Básico';activeProducts=[];individualArea.classList.toggle('hidden',m!=='individual');comboArea.classList.toggle('hidden',m!=='combo');tabInd.classList.toggle('active',m==='individual');tabCombo.classList.toggle('active',m==='combo');render()}
function resetSelection(){selected.clear();selectedAdds.clear();selectedCombo='Básico';activeProducts=[];render()}
function addProduct(){const p=productPicker.value;if(p&&!activeProducts.includes(p)){activeProducts.push(p);renderIndividual()}}
function removeProduct(p){p=decodeURIComponent(p);activeProducts=activeProducts.filter(x=>x!==p);[...selected].forEach(k=>{const o=JSON.parse(k);if(o.product===p)selected.delete(k)});renderIndividual()}
function toggleIndividual(k){selected.has(k)?selected.delete(k):selected.add(k);renderIndividual()}
function toggleAddon(n){selectedAdds.has(n)?selectedAdds.delete(n):selectedAdds.add(n);renderCombo()}
function renderIndividual(){syncProducts();const p=person.value,available=productsForPerson().filter(x=>!activeProducts.includes(x));productPicker.innerHTML=available.length?available.map(x=>`<option>${x}</option>`).join(''):'<option value="">Todos já adicionados</option>';productPicker.disabled=!available.length;individualGroups.innerHTML=activeProducts.map(prod=>{const items=C.individual.filter(x=>x.person===p&&x.product===prod);return `<div class="product-block"><div class="product-head"><div><div class="eyebrow">Produto selecionado</div><b>${prod}</b></div><button class="ghost" onclick="removeProduct('${encodeURIComponent(prod)}')">Remover</button></div><div class="items">${items.map(x=>{const k=JSON.stringify({product:x.product,flag:x.flag});return `<label class="item"><input type="checkbox" ${selected.has(k)?'checked':''} onchange='toggleIndividual(${JSON.stringify(k)})'><span><b>${x.flag}</b><span>${selected.has(k)?'Selecionado':'Clique para incluir'}</span></span></label>`}).join('')}</div></div>`}).join('')}
function renderCombo(){const p=person.value,cs=C.combos.filter(x=>x.person===p);if(!cs.some(x=>x.level===selectedCombo))selectedCombo=cs[0]?.level||'Básico';comboCards.innerHTML=cs.map(c=>`<div class="combo ${c.level===selectedCombo?'active':''}" onclick="selectedCombo='${c.level}';renderCombo()"><h4>${c.level}</h4><ul>${c.items.map(i=>`<li>${i}</li>`).join('')}</ul><button class="${c.level===selectedCombo?'primary':'ghost'}">${c.level===selectedCombo?'Selecionado':'Selecionar'}</button></div>`).join('');const adds=C.addons.filter(x=>x.person===p);comboAdds.innerHTML=adds.map(x=>`<label class="item"><input type="checkbox" ${selectedAdds.has(x.name)?'checked':''} onchange='toggleAddon(${JSON.stringify(x.name)})'><span><b>${x.name}</b><span>${selectedAdds.has(x.name)?'Selecionado':'Opcional'}</span></span></label>`).join('')}
function render(){mode==='individual'?renderIndividual():renderCombo()}
function clientData(){return {company:client.value.trim(),doc:doc.value.trim(),contact:contact.value.trim(),email:clientEmail.value.trim(),phone:phone.value.trim(),focus:focus.value.trim(),objective:objective.value.trim()}}
async function submitRequest(){msg.textContent='';const q=Math.max(0,+qty.value||0),c=clientData(),sel=selection();if(!c.company||!c.contact||!c.email||!q){msg.textContent='Preencha empresa, contato, e-mail e quantidade.';return}if(mode==='individual'&&!sel.length){msg.textContent='Selecione ao menos uma informação.';return}submitBtn.disabled=true;submitBtn.textContent='Enviando…';const {data,error}=await sb.rpc('submit_lead_quote_request',{p_mode:mode,p_person:person.value,p_qty:q,p_client:c,p_selection:sel,p_notes:notes.value.trim()||null});submitBtn.disabled=false;submitBtn.textContent='Solicitar cotação';if(error){msg.textContent='Não foi possível enviar a solicitação. Tente novamente ou fale com a CDL.';console.error(error);return}requestCode.textContent=data.code;formPanel.classList.add('hidden');success.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
render();